// ----------------------------------------------------------------------------
// <copyright file="AppSettingsConstants.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// ----------------------------------------------------------------------------

namespace Relativity.DataExchange
{
	using Relativity.DataExchange.Io;

	/// <summary>
	/// Defines all application settings constant keys and default values.
	/// </summary>
	internal static class AppSettingsConstants
	{
#pragma warning disable SA1600
		// All configuration sections go here.
		public const string SectionLegacykCuraConfig = "kCura.Config";
		public const string SectionLegacyWindowsProcess = "kCura.Windows.Process";
		public const string SectionLegacyUtility = "kCura.Utility";
		public const string SectionLegacyWinEdds = "kCura.WinEDDS";
		public const string SectionDataExchange = "Relativity.DataExchange";

		// All Registry keys go here.
		public const string ForceFolderPreviewRegistryKey = "ForceFolderPreview";
		public const string ObjectFieldIdListContainsArtifactIdRegistryKey = "ObjectFieldIdListContainsArtifactId";
		public const string OpenIdConnectHomeRealmDiscoveryHintKey = "HRDHint";
		public const string WebApiServiceUrlRegistryKey = "WebServiceURL";

		// All default values go here.
		public const string ApplicationNameKey = "ApplicationName";
		public const string ApplicationNameDefaultValue = "";
		public const string AuditLevelKey = "AuditLevel";
		public const string AuditLevelDefaultValue = "FullAudit";
		public const string CreateErrorForInvalidDateKey = "CreateErrorForInvalidDate";
		public const bool CreateErrorForInvalidDateDefaultValue = true;
		public const string CreateErrorForEmptyNativeFileKey = "CreateErrorForEmptyNativeFile";
		public const bool CreateErrorForEmptyNativeFileDefaultValue = false;
		public const string CreateFoldersInWebApiKey = "CreateFoldersInWebAPI";
		public const bool CreateFoldersInWebApiDefaultValue = true;
		public const string DefaultMaxErrorCountKey = "DefaultMaxErrorCount";
		public const int DefaultMaxErrorCountDefaultValue = 1000;
		public const string DisableImageLocationValidationKey = "DisableImageLocationValidation";
		public const bool DisableImageLocationValidationDefaultValue = false;
		public const string DisableImageTypeValidationKey = "DisableImageTypeValidation";
		public const bool DisableImageTypeValidationDefaultValue = false;
		public const string DisableOutsideInFileIdentificationKey = "DisableNativeValidation";
		public const bool DisableOutsideInFileIdentificationDefaultValue = false;
		public const string DisableTextFileEncodingCheckKey = "DisableTextFileEncodingCheck";
		public const bool DisableTextFileEncodingCheckDefaultValue = false;
		public const string DisableThrowOnIllegalCharactersKey = "DisableNativeLocationValidation";
		public const bool DisableThrowOnIllegalCharactersDefaultValue = false;
		public const string DynamicBatchResizingOnKey = "DynamicBatchResizingOn";
		public const bool DynamicBatchResizingOnDefaultValue = true;
		public const string EnableCaseSensitiveSearchOnImportKey = "EnableCaseSensitiveSearchOnImport";
		public const bool EnableCaseSensitiveSearchOnImportDefaultValue = true;
		public const string EnforceVersionCompatibilityCheckKey = "40B88CBC-9435-4A91-8F65-48B52C51B3FD";
		public const bool EnforceVersionCompatibilityCheckDefaultValue = true;
		public const string ExportBatchSizeKey = "ExportBatchSize";
		public const int ExportBatchSizeDefaultValue = 1000;
		public const string ExportErrorNumberOfRetriesKey = "ExportErrorNumberOfRetries";
		public const int ExportErrorNumberOfRetriesDefaultValue = 20;
		public const string ExportErrorWaitTimeInSecondsKey = "ExportErrorWaitTimeInSeconds";
		public const int ExportErrorWaitTimeInSecondsDefaultValue = 30;
		public const string ExportThreadCountKey = "ExportThreadCount";
		public const int ExportThreadCountDefaultValue = 2;
		public const string ExportLongTextBufferSizeBytesKey = "ExportLongTextBufferSizeBytes";
		public const int ExportLongTextBufferSizeBytesDefaultValue = 16384;
		public const int ExportLongTextBufferSizeBytesMinValue = 128;
		public const int ExportLongTextBufferSizeBytesMaxValue = 1048576;
		public const string ExportLongTextLargeFileProgressRateSecondsKey = "ExportLongTextLargeFileProgressRateSeconds";
		public const int ExportLongTextLargeFileProgressRateSecondsDefaultValue = 3;
		public const string ExportLongTextObjectManagerEnabledKey = "ExportLongTextObjectManagerEnabled";
		public const bool ExportLongTextObjectManagerEnabledDefaultValue = true;
		public const string ExportLongTextDataGridThreadCountKey = "ExportLongTextDataGridThreadCount";
		public const int ExportLongTextDataGridThreadCountDefaultValue = 4;
		public const string ExportLongTextSqlThreadCountKey = "ExportLongTextSqlThreadCount";
		public const int ExportLongTextMinThreadCountValue = 1;
		public const int ExportLongTextMaxThreadCountValue = 16;
		public const int ExportLongTextSqlThreadCountDefaultValue = 2;
		public const string FileTypeIdentifyTimeoutSecondsKey = "FileTypeIdentifyTimeoutSeconds";
		public const int FileTypeIdentifyTimeoutSecondsDefaultValue = Relativity.DataExchange.Io.OutsideInFileTypeIdentifierService.DefaultIdleTimeout;
		public const bool ForceFolderPreviewDefaultValue = true;
		public const string ForceWebUploadKey = "ForceWebUpload";
		public const bool ForceWebUploadDefaultValue = false;
		public const string HttpErrorNumberOfRetriesKey = "HttpErrorNumberOfRetries";
		public const int HttpErrorNumberOfRetriesDefaultValue = 20;
		public const int HttpErrorNumberOfRetriesMinValue = 1;
		public const string HttpErrorWaitTimeInSecondsKey = "HttpErrorWaitTimeInSeconds";
		public const int HttpErrorWaitTimeInSecondsDefaultValue = 10;
		public const int HttpErrorWaitTimeInSecondsMinValue = 1;
		public const string HttpTimeoutSecondsKey = "HttpTimeoutSeconds";
		public const int HttpTimeoutSecondsDefaultValue = 300;
		public const int HttpTimeoutSecondsMinValue = 1;
		public const string HttpExtractedTextTimeoutSecondsKey = "HttpExtractedTextTimeoutSeconds";
		public const int HttpExtractedTextTimeoutSecondsDefaultValue = 900;
		public const string ImportBatchMaxVolumeKey = "ImportBatchMaxVolume";
		public const int ImportBatchMaxVolumeDefaultValue = 10485760;
		public const string ImportBatchSizeKey = "ImportBatchSize";
		public const int ImportBatchSizeDefaultValue = 1000;
		public const string IoErrorNumberOfRetriesKey = "IOErrorNumberOfRetries";
		public const int IoErrorNumberOfRetriesDefaultValue = 20;
		public const string IoErrorWaitTimeInSecondsKey = "IOErrorWaitTimeInSeconds";
		public const int IoErrorWaitTimeInSecondsDefaultValue = 30;
		public const string JobCompleteBatchSizeKey = "JobCompleteBatchSize";
		public const int JobCompleteBatchSizeDefaultValue = 50000;
		public const string LoadImportedFullTextFromServerKey = "LoadImportedFullTextFromServer";
		public const bool LoadImportedFullTextFromServerDefaultValue = false;
		public const string LogAllEventsKey = "LogAllEvents";
		public const bool LogAllEventsDefaultValue = false;
		public const string LogConfigXmlFileNameKey = "LogConfigFile";
		public const string LogConfigXmlFileNameDefaultValue = "LogConfig.xml";
		public const string LogHashingEnabledKey = "LogHashingEnabled";
		public const bool LogHashingEnabledDefaultValue = false;
		public const string LogHashingLevelKey = "LogHashingLevel";
		public const string LogHashingLevelDefaultValue = "Error";
		public const string MinBatchSizeKey = "MinimumBatchSize";
		public const int MinBatchSizeDefaultValue = 100;
		public const string MaximumReloginTriesKey = "MaximumReloginTries";
		public const int MaximumReloginTriesDefaultValue = 4;
		public const string OAuth2ImplicitCredentialRedirectUrlKey = "OAuth2ImplicitCredentialRedirectUrl";
		public const string OAuth2ImplicitCredentialRedirectUrlDefaultValue = "rdc://relativityimplicit/";
		public const string PermissionErrorsRetryKey = "PermissionErrorsRetry";
		public const bool PermissionErrorsRetryDefaultValue = false;
		public const string PreviewThresholdKey = "PreviewThreshold";
		public const int PreviewThresholdDefaultValue = 1000;
		public const string ProcessFormRefreshRateKey = "ProcessFormRefreshRate";
		public const int ProcessFormRefreshRateDefaultValue = 0;
		public const RetryOptions RetryOptionsDefaultValue = RetryOptions.Io;
		public const string SuppressServerCertificateValidationKey = "SuppressCertificateCheckOnClient";
		public const bool SuppressServerCertificateValidationDefaultValue = false;
		public const string TapiAsperaBcpRootFolderKey = "TapiAsperaBcpRootFolder";
		public const string TapiAsperaBcpRootFolderDefaultValue = "";
		public const string TapiAsperaNativeDocRootLevelsKey = "TapiAsperaNativeDocRootLevels";
		public const int TapiAsperaNativeDocRootLevelsDefaultValue = 1;
		public const string TapiAsperaDatagramSizeKey = "TapiAsperaDatagramSize";
		public const int TapiAsperaDatagramSizeDefaultValue = 0;
		public const int TapiAsperaDatagramSizeMinimumValue = 296;
		public const int TapiAsperaDatagramSizeMaximumValue = 10000;
		public const string TapiBadPathErrorsRetryKey = "BadPathErrorsRetry";
		public const bool TapiBadPathErrorsRetryDefaultValue = false;
		public const string TapiFileNotFoundErrorsDisabledKey = "TapiFileNotFoundErrorsDisabled";
		public const bool TapiFileNotFoundErrorsDisabledDefaultValue = false;
		public const string TapiFileNotFoundErrorsRetryKey = "TapiFileNotFoundErrorsRetry";
		public const bool TapiFileNotFoundErrorsRetryDefaultValue = true;
		public const string TapiForceAsperaClientKey = "TapiForceAsperaClient";
		public const bool TapiForceAsperaClientDefaultValue = false;
		public const string TapiForceBcpHttpClientKey = "TapiForceBcpHttpClient";
		public const bool TapiForceBcpHttpClientDefaultValue = false;
		public const string TapiForceClientCandidatesKey = "TapiForceClientCandidates";
		public const string TapiForceClientCandidatesDefaultValue = "";
		public const string TapiForceFileShareClientKey = "TapiForceFileShareClient";
		public const bool TapiForceFileShareClientDefaultValue = false;
		public const string TapiForceHttpClientKey = "TapiForceHttpClient";
		public const bool TapiForceHttpClientDefaultValue = false;
		public const string TapiLargeFileProgressEnabledKey = "TapiLargeFileProgressEnabled";
		public const bool TapiLargeFileProgressEnabledDefaultValue = true;
		public const string TapiMaxInactivitySecondsKey = "TapiMaxInactivitySeconds";
		public const int TapiMaxInactivitySecondsDefaultValue = 180;
		public const string TapiMaxJobParallelismKey = "TapiMaxJobParallelism";
		public const int TapiMaxJobParallelismDefaultValue = 10;
		public const string TapiMinDataRateMbpsKey = "TapiMinDataRateMbps";
		public const int TapiMinDataRateMbpsDefaultValue = 0;
		public const string TapiPreserveFileTimestampsKey = "TapiPreserveFileTimestamps";
		public const bool TapiPreserveFileTimestampsDefaultValue = false;
		public const string TapiSubmitApmMetricsKey = "TapiSubmitApmMetrics";
		public const bool TapiSubmitApmMetricsDefaultValue = true;
		public const string TelemetrySubmitApmMetricsKey = "TelemetrySubmitApmMetrics";
		public const bool TelemetrySubmitApmMetricsDefaultValue = true;
		public const string TelemetrySubmitSumMetricsKey = "TelemetrySubmitSumMetrics";
		public const bool TelemetrySubmitSumMetricsDefaultValue = true;
		public const string TelemetryMetricsThrottlingSecondsKey = "TelemetryMetricsThrottlingSeconds";
		public const int TelemetryMetricsThrottlingSecondsDefaultValue = 30;
		public const string TapiTargetDataRateMbpsKey = "TapiTargetDataRateMbps";
		public const string TapiTransferLogDirectoryKey = "TapiTransferLogDirectory";
		public const string TapiTransferLogDirectoryDefaultValue = "";
		public const string TempDirectoryKey = "TempDirectory";
		public const string TempDirectoryDefaultValue = "";
		public const int TapiTargetDataRateMbpsDefaultValue = 100;
		public const string UseOldExportKey = "UseOldExport";
		public const bool UseOldExportDefaultValue = false;
		public const string UsePipeliningForNativeAndObjectImportsKey = "UsePipeliningForNativeAndObjectImports";
		public const bool UsePipeliningForNativeAndObjectImportsDefaultValue = true;
		public const string ValueRefreshThresholdKey = "ValueRefreshThreshold";
		public const int ValueRefreshThresholdDefaultValue = 10000;
		public const string WaitBeforeReconnectKey = "WaitBeforeReconnect";
		public const int WaitBeforeReconnectDefaultValue = 2000;
		public const string WebApiOperationTimeoutKey = "WebAPIOperationTimeout";
		public const int WebApiOperationTimeoutDefaultValue = 600000;
		public const string WebBasedFileDownloadChunkSizeKey = "WebBasedFileDownloadChunkSize";
		public const int WebBasedFileDownloadChunkSizeDefaultValue = 1048576;
		public const int WebBasedFileDownloadChunkSizeMinValue = 1024;
		public const string WebApiServiceUrlKey = "WebServiceURL";
		public const string WebApiServiceUrlDefaultValue = "";
		public const string UseSynchronizedImportBatchModeKey = "UseSynchronizedImportBatchMode";
		public const bool UseSynchronizedImportBatchModeDefaultValue = true;
#pragma warning restore SA1600
	}
}