' -------------------------------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by Update-AssemblyInfo.ps1
'
'     Changes to this file must be made in that script
' </auto-generated>
' -------------------------------------------------------------------------------------------------------

Imports System.Reflection
Imports System.Resources

<assembly: AssemblyCopyright("Relativity")>
<assembly: AssemblyTrademark("Relativity")>
<assembly: AssemblyCulture("")>

' Note: do NOT modify these values! This is automatically stamped by TFS during the CI builds.
<assembly: AssemblyVersion("1.0.0.0")>
<assembly: AssemblyFileVersion("1.0.0.0")>
<assembly: AssemblyConfiguration("Release")>

<assembly: AssemblyCompany("Relativity ODA LLC")>
<assembly: NeutralResourcesLanguage("en-US")>
