[CmdletBinding()]
param(
	[Parameter()]
	[String]$assembly_version = "1.0.0.0",
	[Parameter()]
	[String]$path_to_version_folder = (Split-Path -Parent $MyInvocation.MyCommand.Path)
)

$cs_assemblyInfo = @"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Update-AssemblyInfo.ps1
//
//     Changes to this file must be made in that script
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("$assembly_version")]
[assembly: AssemblyFileVersionAttribute("$assembly_version")]
[assembly: AssemblyCopyrightAttribute("© Relativity")]
[assembly: AssemblyCompanyAttribute("Relativity ODA LLC")]
"@

$path_to_AssemblyInfo_cs = Join-Path $path_to_version_folder "AssemblyInfo.cs"
$cs_assemblyInfo | Set-Content $path_to_AssemblyInfo_cs