trigger:
  branches:
    include:
    - '*'

variables:
- name: unregister.opt-in
  value: true

resources:
  repositories:
    - repository: azdo_templates
      type: github
      name: relativityone/azdo-templates   # organization and name of repo to reference
      endpoint: relativityone
      ref: 'refs/heads/main'   # branch to reference

stages:
- template: libraryci-server.yml@azdo_templates  # pipeline yml file reference
  parameters:
    buildSteps:
      - checkout: self
      - checkout: azdo_templates