'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
'
Namespace kCura.EDDS.WebAPI.FieldManagerBase

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code"), _
	 System.Web.Services.WebServiceBindingAttribute(Name:="FieldManagerSoap", [Namespace]:="http://foley.com/EDDS/FieldManager"), _
	 System.Xml.Serialization.XmlIncludeAttribute(GetType(Artifact))> _
	Partial Public Class FieldManager
		Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

		Private CreateOperationCompleted As System.Threading.SendOrPostCallback

		Private ReadOperationCompleted As System.Threading.SendOrPostCallback

		Private useDefaultCredentialsSetExplicitly As Boolean

		'''<remarks/>
		Public Sub New()
			MyBase.New()
			Me.Url = "http://localhost/EDDSWebAPI/FieldManager.asmx"
			If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
				Me.UseDefaultCredentials = True
				Me.useDefaultCredentialsSetExplicitly = False
			Else
				Me.useDefaultCredentialsSetExplicitly = True
			End If
		End Sub

		Public Shadows Property Url() As String
			Get
				Return MyBase.Url
			End Get
			Set(ByVal value As String)
				If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
								AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
								AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
					MyBase.UseDefaultCredentials = False
				End If
				MyBase.Url = Value
			End Set
		End Property

		Public Shadows Property UseDefaultCredentials() As Boolean
			Get
				Return MyBase.UseDefaultCredentials
			End Get
			Set(ByVal value As Boolean)
				MyBase.UseDefaultCredentials = Value
				Me.useDefaultCredentialsSetExplicitly = True
			End Set
		End Property

		'''<remarks/>
		Public Event CreateCompleted As CreateCompletedEventHandler

		'''<remarks/>
		Public Event ReadCompleted As ReadCompletedEventHandler

		'''<remarks/>
		<System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://foley.com/EDDS/FieldManager/Create", RequestNamespace:="http://foley.com/EDDS/FieldManager", ResponseNamespace:="http://foley.com/EDDS/FieldManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Function Create(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field) As Integer
			Dim results() As Object = Me.Invoke("Create", New Object() {caseContextArtifactID, fieldDTO})
			Return CType(results(0), Integer)
		End Function

		'''<remarks/>
		Public Function BeginCreate(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("Create", New Object() {caseContextArtifactID, fieldDTO}, callback, asyncState)
		End Function

		'''<remarks/>
		Public Function EndCreate(ByVal asyncResult As System.IAsyncResult) As Integer
			Dim results() As Object = Me.EndInvoke(asyncResult)
			Return CType(results(0), Integer)
		End Function

		'''<remarks/>
		Public Overloads Sub CreateAsync(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field)
			Me.CreateAsync(caseContextArtifactID, fieldDTO, Nothing)
		End Sub

		'''<remarks/>
		Public Overloads Sub CreateAsync(ByVal caseContextArtifactID As Integer, ByVal fieldDTO As Field, ByVal userState As Object)
			If (Me.CreateOperationCompleted Is Nothing) Then
				Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
			End If
			Me.InvokeAsync("Create", New Object() {caseContextArtifactID, fieldDTO}, Me.CreateOperationCompleted, userState)
		End Sub

		Private Sub OnCreateOperationCompleted(ByVal arg As Object)
			If (Not (Me.CreateCompletedEvent) Is Nothing) Then
				Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
				RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
			End If
		End Sub

		'''<remarks/>
		<System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://foley.com/EDDS/FieldManager/Read", RequestNamespace:="http://foley.com/EDDS/FieldManager", ResponseNamespace:="http://foley.com/EDDS/FieldManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
		Public Function Read(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer) As Field
			Dim results() As Object = Me.Invoke("Read", New Object() {caseContextArtifactID, fieldArtifactID})
			Return CType(results(0), Field)
		End Function

		'''<remarks/>
		Public Function BeginRead(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
			Return Me.BeginInvoke("Read", New Object() {caseContextArtifactID, fieldArtifactID}, callback, asyncState)
		End Function

		'''<remarks/>
		Public Function EndRead(ByVal asyncResult As System.IAsyncResult) As Field
			Dim results() As Object = Me.EndInvoke(asyncResult)
			Return CType(results(0), Field)
		End Function

		'''<remarks/>
		Public Overloads Sub ReadAsync(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer)
			Me.ReadAsync(caseContextArtifactID, fieldArtifactID, Nothing)
		End Sub

		'''<remarks/>
		Public Overloads Sub ReadAsync(ByVal caseContextArtifactID As Integer, ByVal fieldArtifactID As Integer, ByVal userState As Object)
			If (Me.ReadOperationCompleted Is Nothing) Then
				Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
			End If
			Me.InvokeAsync("Read", New Object() {caseContextArtifactID, fieldArtifactID}, Me.ReadOperationCompleted, userState)
		End Sub

		Private Sub OnReadOperationCompleted(ByVal arg As Object)
			If (Not (Me.ReadCompletedEvent) Is Nothing) Then
				Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
				RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
			End If
		End Sub

		'''<remarks/>
		Public Shadows Sub CancelAsync(ByVal userState As Object)
			MyBase.CancelAsync(userState)
		End Sub

		Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
			If ((url Is Nothing) _
							OrElse (url Is String.Empty)) Then
				Return False
			End If
			Dim wsUri As System.Uri = New System.Uri(url)
			If ((wsUri.Port >= 1024) _
							AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
				Return True
			End If
			Return False
		End Function
	End Class

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"), _
	 System.SerializableAttribute(), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code"), _
	 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foley.com/EDDS/FieldManager")> _
	Partial Public Class Field
		Inherits Artifact

		Private fieldArtifactTypeIDField As Integer

		Private displayNameField As String

		Private fieldTypeIDField As Integer

		Private fieldTypeField As FieldType

		Private fieldCategoryIDField As Integer

		Private fieldCategoryField As FieldCategory

		Private artifactViewFieldIDField As Integer

		Private codeTypeIDField As System.Nullable(Of Integer)

		Private maxLengthField As System.Nullable(Of Integer)

		Private isRequiredField As Boolean

		Private isRemovableField As Boolean

		Private isEditableField As Boolean

		Private isVisibleField As Boolean

		Private isArtifactBaseFieldField As Boolean

		Private valueField As Object

		Private tableNameField As String

		Private columnNameField As String

		Private isReadOnlyInLayoutField As Boolean

		Private filterTypeField As String

		Private fieldDisplayTypeIDField As Integer

		Private rowsField As Integer

		Private isLinkedField As Boolean

		Private formatStringField As String

		Private repeatColumnField As System.Nullable(Of Integer)

		Private associativeArtifactTypeIDField As System.Nullable(Of Integer)

		Private isAvailableToAssociativeObjectsField As Boolean

		Private isAvailableInChoiceTreeField As Boolean

		Private isGroupByEnabledField As Boolean

		Private isIndexEnabledField As Boolean

		Private displayValueTrueField As String

		Private displayValueFalseField As String

		Private widthField As String

		Private wrappingField As Boolean

		Private linkLayoutArtifactIDField As Integer

		Private nameValueField As String

		Private linkTypeField As Boolean

		Private useUnicodeEncodingField As Boolean

		Private allowHtmlField As Boolean

		Private isSortableField As Boolean

		Private friendlyNameField As String

		Private relationalIndexViewArtifactIDField As System.Nullable(Of Integer)

		Private objectsFieldArgsField As ObjectsFieldParameters

		'''<remarks/>
		Public Property FieldArtifactTypeID() As Integer
			Get
				Return Me.fieldArtifactTypeIDField
			End Get
			Set(ByVal value As Integer)
				Me.fieldArtifactTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property DisplayName() As String
			Get
				Return Me.displayNameField
			End Get
			Set(ByVal value As String)
				Me.displayNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldTypeID() As Integer
			Get
				Return Me.fieldTypeIDField
			End Get
			Set(ByVal value As Integer)
				Me.fieldTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldType() As FieldType
			Get
				Return Me.fieldTypeField
			End Get
			Set(ByVal value As FieldType)
				Me.fieldTypeField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldCategoryID() As Integer
			Get
				Return Me.fieldCategoryIDField
			End Get
			Set(ByVal value As Integer)
				Me.fieldCategoryIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldCategory() As FieldCategory
			Get
				Return Me.fieldCategoryField
			End Get
			Set(ByVal value As FieldCategory)
				Me.fieldCategoryField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property ArtifactViewFieldID() As Integer
			Get
				Return Me.artifactViewFieldIDField
			End Get
			Set(ByVal value As Integer)
				Me.artifactViewFieldIDField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property CodeTypeID() As System.Nullable(Of Integer)
			Get
				Return Me.codeTypeIDField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.codeTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property MaxLength() As System.Nullable(Of Integer)
			Get
				Return Me.maxLengthField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.maxLengthField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsRequired() As Boolean
			Get
				Return Me.isRequiredField
			End Get
			Set(ByVal value As Boolean)
				Me.isRequiredField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsRemovable() As Boolean
			Get
				Return Me.isRemovableField
			End Get
			Set(ByVal value As Boolean)
				Me.isRemovableField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsEditable() As Boolean
			Get
				Return Me.isEditableField
			End Get
			Set(ByVal value As Boolean)
				Me.isEditableField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsVisible() As Boolean
			Get
				Return Me.isVisibleField
			End Get
			Set(ByVal value As Boolean)
				Me.isVisibleField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsArtifactBaseField() As Boolean
			Get
				Return Me.isArtifactBaseFieldField
			End Get
			Set(ByVal value As Boolean)
				Me.isArtifactBaseFieldField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Value() As Object
			Get
				Return Me.valueField
			End Get
			Set(ByVal value As Object)
				Me.valueField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property TableName() As String
			Get
				Return Me.tableNameField
			End Get
			Set(ByVal value As String)
				Me.tableNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property ColumnName() As String
			Get
				Return Me.columnNameField
			End Get
			Set(ByVal value As String)
				Me.columnNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsReadOnlyInLayout() As Boolean
			Get
				Return Me.isReadOnlyInLayoutField
			End Get
			Set(ByVal value As Boolean)
				Me.isReadOnlyInLayoutField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FilterType() As String
			Get
				Return Me.filterTypeField
			End Get
			Set(ByVal value As String)
				Me.filterTypeField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldDisplayTypeID() As Integer
			Get
				Return Me.fieldDisplayTypeIDField
			End Get
			Set(ByVal value As Integer)
				Me.fieldDisplayTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Rows() As Integer
			Get
				Return Me.rowsField
			End Get
			Set(ByVal value As Integer)
				Me.rowsField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsLinked() As Boolean
			Get
				Return Me.isLinkedField
			End Get
			Set(ByVal value As Boolean)
				Me.isLinkedField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FormatString() As String
			Get
				Return Me.formatStringField
			End Get
			Set(ByVal value As String)
				Me.formatStringField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property RepeatColumn() As System.Nullable(Of Integer)
			Get
				Return Me.repeatColumnField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.repeatColumnField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property AssociativeArtifactTypeID() As System.Nullable(Of Integer)
			Get
				Return Me.associativeArtifactTypeIDField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.associativeArtifactTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsAvailableToAssociativeObjects() As Boolean
			Get
				Return Me.isAvailableToAssociativeObjectsField
			End Get
			Set(ByVal value As Boolean)
				Me.isAvailableToAssociativeObjectsField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsAvailableInChoiceTree() As Boolean
			Get
				Return Me.isAvailableInChoiceTreeField
			End Get
			Set(ByVal value As Boolean)
				Me.isAvailableInChoiceTreeField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsGroupByEnabled() As Boolean
			Get
				Return Me.isGroupByEnabledField
			End Get
			Set(ByVal value As Boolean)
				Me.isGroupByEnabledField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsIndexEnabled() As Boolean
			Get
				Return Me.isIndexEnabledField
			End Get
			Set(ByVal value As Boolean)
				Me.isIndexEnabledField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property DisplayValueTrue() As String
			Get
				Return Me.displayValueTrueField
			End Get
			Set(ByVal value As String)
				Me.displayValueTrueField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property DisplayValueFalse() As String
			Get
				Return Me.displayValueFalseField
			End Get
			Set(ByVal value As String)
				Me.displayValueFalseField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Width() As String
			Get
				Return Me.widthField
			End Get
			Set(ByVal value As String)
				Me.widthField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Wrapping() As Boolean
			Get
				Return Me.wrappingField
			End Get
			Set(ByVal value As Boolean)
				Me.wrappingField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property LinkLayoutArtifactID() As Integer
			Get
				Return Me.linkLayoutArtifactIDField
			End Get
			Set(ByVal value As Integer)
				Me.linkLayoutArtifactIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property NameValue() As String
			Get
				Return Me.nameValueField
			End Get
			Set(ByVal value As String)
				Me.nameValueField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property LinkType() As Boolean
			Get
				Return Me.linkTypeField
			End Get
			Set(ByVal value As Boolean)
				Me.linkTypeField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property UseUnicodeEncoding() As Boolean
			Get
				Return Me.useUnicodeEncodingField
			End Get
			Set(ByVal value As Boolean)
				Me.useUnicodeEncodingField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property AllowHtml() As Boolean
			Get
				Return Me.allowHtmlField
			End Get
			Set(ByVal value As Boolean)
				Me.allowHtmlField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property IsSortable() As Boolean
			Get
				Return Me.isSortableField
			End Get
			Set(ByVal value As Boolean)
				Me.isSortableField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FriendlyName() As String
			Get
				Return Me.friendlyNameField
			End Get
			Set(ByVal value As String)
				Me.friendlyNameField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property RelationalIndexViewArtifactID() As System.Nullable(Of Integer)
			Get
				Return Me.relationalIndexViewArtifactIDField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.relationalIndexViewArtifactIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property ObjectsFieldArgs() As ObjectsFieldParameters
			Get
				Return Me.objectsFieldArgsField
			End Get
			Set(ByVal value As ObjectsFieldParameters)
				Me.objectsFieldArgsField = Value
			End Set
		End Property
	End Class

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"), _
	 System.SerializableAttribute(), _
	 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foley.com/EDDS/FieldManager")> _
	Public Enum FieldType

		'''<remarks/>
		Varchar

		'''<remarks/>
		[Integer]

		'''<remarks/>
		[Date]

		'''<remarks/>
		[Boolean]

		'''<remarks/>
		Text

		'''<remarks/>
		Code

		'''<remarks/>
		[Decimal]

		'''<remarks/>
		Currency

		'''<remarks/>
		MultiCode

		'''<remarks/>
		File

		'''<remarks/>
		[Object]

		'''<remarks/>
		User

		'''<remarks/>
		LayoutText

		'''<remarks/>
		Objects
	End Enum

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"), _
	 System.SerializableAttribute(), _
	 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foley.com/EDDS/FieldManager")> _
	Public Enum FieldCategory

		'''<remarks/>
		Generic

		'''<remarks/>
		FullText

		'''<remarks/>
		Identifier

		'''<remarks/>
		Reflected

		'''<remarks/>
		Comments

		'''<remarks/>
		Relational

		'''<remarks/>
		ProductionMarker

		'''<remarks/>
		AutoCreate

		'''<remarks/>
		FileSize

		'''<remarks/>
		FolderName

		'''<remarks/>
		FileInfo

		'''<remarks/>
		ParentArtifact

		'''<remarks/>
		MarkupSetMarker

		'''<remarks/>
		GenericSystem

		'''<remarks/>
		MultiReflected

		'''<remarks/>
		Batch
	End Enum

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"), _
	 System.SerializableAttribute(), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code"), _
	 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foley.com/EDDS/FieldManager")> _
	Partial Public Class ObjectsFieldParameters

		Private siblingFieldNameField As String

		Private fieldSchemaColumnNameField As String

		Private siblingFieldSchemaColumnNameField As String

		Private relationalTableSchemaNameField As String

		'''<remarks/>
		Public Property SiblingFieldName() As String
			Get
				Return Me.siblingFieldNameField
			End Get
			Set(ByVal value As String)
				Me.siblingFieldNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property FieldSchemaColumnName() As String
			Get
				Return Me.fieldSchemaColumnNameField
			End Get
			Set(ByVal value As String)
				Me.fieldSchemaColumnNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property SiblingFieldSchemaColumnName() As String
			Get
				Return Me.siblingFieldSchemaColumnNameField
			End Get
			Set(ByVal value As String)
				Me.siblingFieldSchemaColumnNameField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property RelationalTableSchemaName() As String
			Get
				Return Me.relationalTableSchemaNameField
			End Get
			Set(ByVal value As String)
				Me.relationalTableSchemaNameField = Value
			End Set
		End Property
	End Class

	'''<remarks/>
	<System.Xml.Serialization.XmlIncludeAttribute(GetType(Field)), _
	 System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"), _
	 System.SerializableAttribute(), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code"), _
	 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://foley.com/EDDS/FieldManager")> _
	Partial Public Class Artifact

		Private artifactIDField As Integer

		Private artifactTypeIDField As Integer

		Private parentArtifactIDField As System.Nullable(Of Integer)

		Private containerIDField As System.Nullable(Of Integer)

		Private accessControlListIDField As Integer

		Private accessControlListIsInheritedField As Boolean

		Private keywordsField As String

		Private notesField As String

		Private textIdentifierField As String

		Private lastModifiedOnField As Date

		Private lastModifiedByField As Integer

		Private createdByField As Integer

		Private createdOnField As Date

		Private deleteFlagField As Boolean

		'''<remarks/>
		Public Property ArtifactID() As Integer
			Get
				Return Me.artifactIDField
			End Get
			Set(ByVal value As Integer)
				Me.artifactIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property ArtifactTypeID() As Integer
			Get
				Return Me.artifactTypeIDField
			End Get
			Set(ByVal value As Integer)
				Me.artifactTypeIDField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property ParentArtifactID() As System.Nullable(Of Integer)
			Get
				Return Me.parentArtifactIDField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.parentArtifactIDField = Value
			End Set
		End Property

		'''<remarks/>
		<System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
		Public Property ContainerID() As System.Nullable(Of Integer)
			Get
				Return Me.containerIDField
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.containerIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property AccessControlListID() As Integer
			Get
				Return Me.accessControlListIDField
			End Get
			Set(ByVal value As Integer)
				Me.accessControlListIDField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property AccessControlListIsInherited() As Boolean
			Get
				Return Me.accessControlListIsInheritedField
			End Get
			Set(ByVal value As Boolean)
				Me.accessControlListIsInheritedField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Keywords() As String
			Get
				Return Me.keywordsField
			End Get
			Set(ByVal value As String)
				Me.keywordsField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property Notes() As String
			Get
				Return Me.notesField
			End Get
			Set(ByVal value As String)
				Me.notesField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property TextIdentifier() As String
			Get
				Return Me.textIdentifierField
			End Get
			Set(ByVal value As String)
				Me.textIdentifierField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property LastModifiedOn() As Date
			Get
				Return Me.lastModifiedOnField
			End Get
			Set(ByVal value As Date)
				Me.lastModifiedOnField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property LastModifiedBy() As Integer
			Get
				Return Me.lastModifiedByField
			End Get
			Set(ByVal value As Integer)
				Me.lastModifiedByField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property CreatedBy() As Integer
			Get
				Return Me.createdByField
			End Get
			Set(ByVal value As Integer)
				Me.createdByField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property CreatedOn() As Date
			Get
				Return Me.createdOnField
			End Get
			Set(ByVal value As Date)
				Me.createdOnField = Value
			End Set
		End Property

		'''<remarks/>
		Public Property DeleteFlag() As Boolean
			Get
				Return Me.deleteFlagField
			End Get
			Set(ByVal value As Boolean)
				Me.deleteFlagField = Value
			End Set
		End Property
	End Class

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")> _
	Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code")> _
	Partial Public Class CreateCompletedEventArgs
		Inherits System.ComponentModel.AsyncCompletedEventArgs

		Private results() As Object

		Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
			MyBase.New(exception, cancelled, userState)
			Me.results = results
		End Sub

		'''<remarks/>
		Public ReadOnly Property Result() As Integer
			Get
				Me.RaiseExceptionIfNecessary()
				Return CType(Me.results(0), Integer)
			End Get
		End Property
	End Class

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")> _
	Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)

	'''<remarks/>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"), _
	 System.Diagnostics.DebuggerStepThroughAttribute(), _
	 System.ComponentModel.DesignerCategoryAttribute("code")> _
	Partial Public Class ReadCompletedEventArgs
		Inherits System.ComponentModel.AsyncCompletedEventArgs

		Private results() As Object

		Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
			MyBase.New(exception, cancelled, userState)
			Me.results = results
		End Sub

		'''<remarks/>
		Public ReadOnly Property Result() As Field
			Get
				Me.RaiseExceptionIfNecessary()
				Return CType(Me.results(0), Field)
			End Get
		End Property
	End Class
End Namespace
