//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relativity.Import.Export.Services
{
	public enum ExecutionSource
	{

		Unknown = 0,

		Rdc = 1,

		ImportAPI = 2,

		RIP = 3,

		Processing = 4,
	}
}