//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relativity.Import.Export.Services
{
	using System;

	[Serializable]
	public sealed class FolderInfo
	{
		public FolderInfo()
		{
		}

		public int ArtifactID { get; set; }

		public string Name { get; set; }

		public Relativity.Import.Export.Services.FolderInfo Parent { get; set; }

		public int ParentArtifactID { get; set; }
	}
}