'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2407
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2407.
'
Namespace kCura.EDDS.WebAPI.ObjectManagerBase
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ObjectManagerSoap", [Namespace]:="http://www.kCura.com/EDDS/ObjectManager")>  _
    Public Class ObjectManager
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/EDDSWebAPI/ObjectManager.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/ObjectManager/RetrieveArtifactIdOfMappedObject", RequestNamespace:="http://www.kCura.com/EDDS/ObjectManager", ResponseNamespace:="http://www.kCura.com/EDDS/ObjectManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveArtifactIdOfMappedObject(ByVal caseContextArtifactID As Integer, ByVal textIdentifier As String, ByVal artifactTypeID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetrieveArtifactIdOfMappedObject", New Object() {caseContextArtifactID, textIdentifier, artifactTypeID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveArtifactIdOfMappedObject(ByVal caseContextArtifactID As Integer, ByVal textIdentifier As String, ByVal artifactTypeID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveArtifactIdOfMappedObject", New Object() {caseContextArtifactID, textIdentifier, artifactTypeID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveArtifactIdOfMappedObject(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/ObjectManager/RetrieveArtifactIdOfMappedParentObject", RequestNamespace:="http://www.kCura.com/EDDS/ObjectManager", ResponseNamespace:="http://www.kCura.com/EDDS/ObjectManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveArtifactIdOfMappedParentObject(ByVal caseContextArtifactID As Integer, ByVal textIdentifier As String, ByVal artifactTypeID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetrieveArtifactIdOfMappedParentObject", New Object() {caseContextArtifactID, textIdentifier, artifactTypeID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveArtifactIdOfMappedParentObject(ByVal caseContextArtifactID As Integer, ByVal textIdentifier As String, ByVal artifactTypeID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveArtifactIdOfMappedParentObject", New Object() {caseContextArtifactID, textIdentifier, artifactTypeID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveArtifactIdOfMappedParentObject(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
