'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4927.
'
Namespace kCura.EDDS.WebAPI.TemplateManagerBase
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TemplateManagerSoap", [Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class TemplateManager
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InstallTemplateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/EDDSWebAPI/TemplateManager.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InstallTemplateCompleted As InstallTemplateCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/InstallTemplate", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InstallTemplate(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters) As ApplicationInstallationResult
            Dim results() As Object = Me.Invoke("InstallTemplate", New Object() {template, installationParameters})
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Function BeginInstallTemplate(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InstallTemplate", New Object() {template, installationParameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndInstallTemplate(ByVal asyncResult As System.IAsyncResult) As ApplicationInstallationResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InstallTemplateAsync(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters)
            Me.InstallTemplateAsync(template, installationParameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InstallTemplateAsync(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters, ByVal userState As Object)
            If (Me.InstallTemplateOperationCompleted Is Nothing) Then
                Me.InstallTemplateOperationCompleted = AddressOf Me.OnInstallTemplateOperationCompleted
            End If
            Me.InvokeAsync("InstallTemplate", New Object() {template, installationParameters}, Me.InstallTemplateOperationCompleted, userState)
        End Sub
        
        Private Sub OnInstallTemplateOperationCompleted(ByVal arg As Object)
            If (Not (Me.InstallTemplateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InstallTemplateCompleted(Me, New InstallTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationInstallationParameters
        
        Private caseIdField As Integer
        
        '''<remarks/>
        Public Property CaseId() As Integer
            Get
                Return Me.caseIdField
            End Get
            Set
                Me.caseIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationArtifact
        
        Private artifactIdField As Integer
        
        Private guidField As System.Guid
        
        Private nameField As String
        
        Private typeField As ApplicationArtifactType
        
        '''<remarks/>
        Public Property ArtifactId() As Integer
            Get
                Return Me.artifactIdField
            End Get
            Set
                Me.artifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Guid() As System.Guid
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As ApplicationArtifactType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Public Enum ApplicationArtifactType
        
        '''<remarks/>
        [Case]
        
        '''<remarks/>
        Code
        
        '''<remarks/>
        Field
        
        '''<remarks/>
        Layout
        
        '''<remarks/>
        [Object]
        
        '''<remarks/>
        Rule
        
        '''<remarks/>
        Sync
        
        '''<remarks/>
        Tab
        
        '''<remarks/>
        View
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationInstallationResult
        
        Private exceptionMessageField As String
        
        Private newApplicationArtifactsField() As ApplicationArtifact
        
        Private successField As Boolean
        
        Private updatedApplicationArtifactsField() As ApplicationArtifact
        
        '''<remarks/>
        Public Property ExceptionMessage() As String
            Get
                Return Me.exceptionMessageField
            End Get
            Set
                Me.exceptionMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NewApplicationArtifacts() As ApplicationArtifact()
            Get
                Return Me.newApplicationArtifactsField
            End Get
            Set
                Me.newApplicationArtifactsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedApplicationArtifacts() As ApplicationArtifact()
            Get
                Return Me.updatedApplicationArtifactsField
            End Get
            Set
                Me.updatedApplicationArtifactsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")>  _
    Public Delegate Sub InstallTemplateCompletedEventHandler(ByVal sender As Object, ByVal e As InstallTemplateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InstallTemplateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ApplicationInstallationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ApplicationInstallationResult)
            End Get
        End Property
    End Class
End Namespace
