'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
'
Namespace kCura.EDDS.WebAPI.TemplateManagerBase
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TemplateManagerSoap", [Namespace]:="http://www.kCura.com/EDDS/TemplateManager"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ApplicationBase)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResolveArtifact())),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(FieldKVP()))>  _
    Partial Public Class TemplateManager
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetAppMappingDataForWorkspaceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InstallTemplateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ResolveConflictsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAvailableObjectsForMappingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetAvailableFieldsForMappingOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/RelativityWebApi/TemplateManager.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetAppMappingDataForWorkspaceCompleted As GetAppMappingDataForWorkspaceCompletedEventHandler
        
        '''<remarks/>
        Public Event InstallTemplateCompleted As InstallTemplateCompletedEventHandler
        
        '''<remarks/>
        Public Event ResolveConflictsCompleted As ResolveConflictsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAvailableObjectsForMappingCompleted As GetAvailableObjectsForMappingCompletedEventHandler
        
        '''<remarks/>
        Public Event GetAvailableFieldsForMappingCompleted As GetAvailableFieldsForMappingCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/GetAppMappingDataForWorkspace", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAppMappingDataForWorkspace(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters) As AppMappingData
            Dim results() As Object = Me.Invoke("GetAppMappingDataForWorkspace", New Object() {template, installationParameters})
            Return CType(results(0),AppMappingData)
        End Function
        
        '''<remarks/>
        Public Function BeginGetAppMappingDataForWorkspace(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAppMappingDataForWorkspace", New Object() {template, installationParameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAppMappingDataForWorkspace(ByVal asyncResult As System.IAsyncResult) As AppMappingData
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),AppMappingData)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAppMappingDataForWorkspaceAsync(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters)
            Me.GetAppMappingDataForWorkspaceAsync(template, installationParameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAppMappingDataForWorkspaceAsync(ByVal template As System.Xml.XmlNode, ByVal installationParameters As ApplicationInstallationParameters, ByVal userState As Object)
            If (Me.GetAppMappingDataForWorkspaceOperationCompleted Is Nothing) Then
                Me.GetAppMappingDataForWorkspaceOperationCompleted = AddressOf Me.OnGetAppMappingDataForWorkspaceOperationCompleted
            End If
            Me.InvokeAsync("GetAppMappingDataForWorkspace", New Object() {template, installationParameters}, Me.GetAppMappingDataForWorkspaceOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAppMappingDataForWorkspaceOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAppMappingDataForWorkspaceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAppMappingDataForWorkspaceCompleted(Me, New GetAppMappingDataForWorkspaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/InstallTemplate", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InstallTemplate(ByVal appsToOverride() As Integer, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal packageData() As Byte, ByVal installationParameters As ApplicationInstallationParameters) As ApplicationInstallationResult
            Dim results() As Object = Me.Invoke("InstallTemplate", New Object() {appsToOverride, packageData, installationParameters})
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Function BeginInstallTemplate(ByVal appsToOverride() As Integer, ByVal packageData() As Byte, ByVal installationParameters As ApplicationInstallationParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("InstallTemplate", New Object() {appsToOverride, packageData, installationParameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndInstallTemplate(ByVal asyncResult As System.IAsyncResult) As ApplicationInstallationResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InstallTemplateAsync(ByVal appsToOverride() As Integer, ByVal packageData() As Byte, ByVal installationParameters As ApplicationInstallationParameters)
            Me.InstallTemplateAsync(appsToOverride, packageData, installationParameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InstallTemplateAsync(ByVal appsToOverride() As Integer, ByVal packageData() As Byte, ByVal installationParameters As ApplicationInstallationParameters, ByVal userState As Object)
            If (Me.InstallTemplateOperationCompleted Is Nothing) Then
                Me.InstallTemplateOperationCompleted = AddressOf Me.OnInstallTemplateOperationCompleted
            End If
            Me.InvokeAsync("InstallTemplate", New Object() {appsToOverride, packageData, installationParameters}, Me.InstallTemplateOperationCompleted, userState)
        End Sub
        
        Private Sub OnInstallTemplateOperationCompleted(ByVal arg As Object)
            If (Not (Me.InstallTemplateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InstallTemplateCompleted(Me, New InstallTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/ResolveConflicts", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ResolveConflicts(ByVal appsToOverride() As Integer, ByVal resolveArtifacts() As ResolveArtifact, ByVal installationParameters As ApplicationInstallationParameters) As ApplicationInstallationResult
            Dim results() As Object = Me.Invoke("ResolveConflicts", New Object() {appsToOverride, resolveArtifacts, installationParameters})
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Function BeginResolveConflicts(ByVal appsToOverride() As Integer, ByVal resolveArtifacts() As ResolveArtifact, ByVal installationParameters As ApplicationInstallationParameters, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ResolveConflicts", New Object() {appsToOverride, resolveArtifacts, installationParameters}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndResolveConflicts(ByVal asyncResult As System.IAsyncResult) As ApplicationInstallationResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ApplicationInstallationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ResolveConflictsAsync(ByVal appsToOverride() As Integer, ByVal resolveArtifacts() As ResolveArtifact, ByVal installationParameters As ApplicationInstallationParameters)
            Me.ResolveConflictsAsync(appsToOverride, resolveArtifacts, installationParameters, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ResolveConflictsAsync(ByVal appsToOverride() As Integer, ByVal resolveArtifacts() As ResolveArtifact, ByVal installationParameters As ApplicationInstallationParameters, ByVal userState As Object)
            If (Me.ResolveConflictsOperationCompleted Is Nothing) Then
                Me.ResolveConflictsOperationCompleted = AddressOf Me.OnResolveConflictsOperationCompleted
            End If
            Me.InvokeAsync("ResolveConflicts", New Object() {appsToOverride, resolveArtifacts, installationParameters}, Me.ResolveConflictsOperationCompleted, userState)
        End Sub
        
        Private Sub OnResolveConflictsOperationCompleted(ByVal arg As Object)
            If (Not (Me.ResolveConflictsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ResolveConflictsCompleted(Me, New ResolveConflictsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/GetAvailableObjectsForMapping", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAvailableObjectsForMapping(ByVal workspaceID As Integer, ByVal objectGuids() As System.Guid) As ObjectGuidToName()
            Dim results() As Object = Me.Invoke("GetAvailableObjectsForMapping", New Object() {workspaceID, objectGuids})
            Return CType(results(0),ObjectGuidToName())
        End Function
        
        '''<remarks/>
        Public Function BeginGetAvailableObjectsForMapping(ByVal workspaceID As Integer, ByVal objectGuids() As System.Guid, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAvailableObjectsForMapping", New Object() {workspaceID, objectGuids}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAvailableObjectsForMapping(ByVal asyncResult As System.IAsyncResult) As ObjectGuidToName()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ObjectGuidToName())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAvailableObjectsForMappingAsync(ByVal workspaceID As Integer, ByVal objectGuids() As System.Guid)
            Me.GetAvailableObjectsForMappingAsync(workspaceID, objectGuids, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAvailableObjectsForMappingAsync(ByVal workspaceID As Integer, ByVal objectGuids() As System.Guid, ByVal userState As Object)
            If (Me.GetAvailableObjectsForMappingOperationCompleted Is Nothing) Then
                Me.GetAvailableObjectsForMappingOperationCompleted = AddressOf Me.OnGetAvailableObjectsForMappingOperationCompleted
            End If
            Me.InvokeAsync("GetAvailableObjectsForMapping", New Object() {workspaceID, objectGuids}, Me.GetAvailableObjectsForMappingOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAvailableObjectsForMappingOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAvailableObjectsForMappingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAvailableObjectsForMappingCompleted(Me, New GetAvailableObjectsForMappingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.kCura.com/EDDS/TemplateManager/GetAvailableFieldsForMapping", RequestNamespace:="http://www.kCura.com/EDDS/TemplateManager", ResponseNamespace:="http://www.kCura.com/EDDS/TemplateManager", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAvailableFieldsForMapping(ByVal workspaceID As Integer, ByVal objectGuid As System.Guid, ByVal fieldElements() As FieldElement, ByVal artifactTypeToGuidsMap() As ArtifactTypeIDToObjectGuids) As ObjectValidationResult
            Dim results() As Object = Me.Invoke("GetAvailableFieldsForMapping", New Object() {workspaceID, objectGuid, fieldElements, artifactTypeToGuidsMap})
            Return CType(results(0),ObjectValidationResult)
        End Function
        
        '''<remarks/>
        Public Function BeginGetAvailableFieldsForMapping(ByVal workspaceID As Integer, ByVal objectGuid As System.Guid, ByVal fieldElements() As FieldElement, ByVal artifactTypeToGuidsMap() As ArtifactTypeIDToObjectGuids, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAvailableFieldsForMapping", New Object() {workspaceID, objectGuid, fieldElements, artifactTypeToGuidsMap}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndGetAvailableFieldsForMapping(ByVal asyncResult As System.IAsyncResult) As ObjectValidationResult
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),ObjectValidationResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetAvailableFieldsForMappingAsync(ByVal workspaceID As Integer, ByVal objectGuid As System.Guid, ByVal fieldElements() As FieldElement, ByVal artifactTypeToGuidsMap() As ArtifactTypeIDToObjectGuids)
            Me.GetAvailableFieldsForMappingAsync(workspaceID, objectGuid, fieldElements, artifactTypeToGuidsMap, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetAvailableFieldsForMappingAsync(ByVal workspaceID As Integer, ByVal objectGuid As System.Guid, ByVal fieldElements() As FieldElement, ByVal artifactTypeToGuidsMap() As ArtifactTypeIDToObjectGuids, ByVal userState As Object)
            If (Me.GetAvailableFieldsForMappingOperationCompleted Is Nothing) Then
                Me.GetAvailableFieldsForMappingOperationCompleted = AddressOf Me.OnGetAvailableFieldsForMappingOperationCompleted
            End If
            Me.InvokeAsync("GetAvailableFieldsForMapping", New Object() {workspaceID, objectGuid, fieldElements, artifactTypeToGuidsMap}, Me.GetAvailableFieldsForMappingOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetAvailableFieldsForMappingOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetAvailableFieldsForMappingCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetAvailableFieldsForMappingCompleted(Me, New GetAvailableFieldsForMappingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationInstallationParameters
        
        Private caseIdField As Integer
        
        '''<remarks/>
        Public Property CaseId() As Integer
            Get
                Return Me.caseIdField
            End Get
            Set
                Me.caseIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class FieldToFieldsMap
        
        Private fieldGuidField As System.Guid
        
        Private fieldsField() As FieldElement
        
        '''<remarks/>
        Public Property FieldGuid() As System.Guid
            Get
                Return Me.fieldGuidField
            End Get
            Set
                Me.fieldGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Fields")>  _
        Public Property Fields() As FieldElement()
            Get
                Return Me.fieldsField
            End Get
            Set
                Me.fieldsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class FieldElement
        
        Private allowHTMLField As Boolean
        
        Private artifactIdField As Integer
        
        Private artifactViewFieldIdField As Integer
        
        Private associativeArtifactTypeIdField As System.Nullable(Of Integer)
        
        Private codesField() As CodeElement
        
        Private codeTypeIdField As System.Nullable(Of Integer)
        
        Private connectorFieldArtifactIdField As System.Nullable(Of Integer)
        
        Private displayNameField As String
        
        Private displayValueFalseField As String
        
        Private displayValueTrueField As String
        
        Private fieldArtifactTypeIdField As Integer
        
        Private fieldCategoryIdField As Integer
        
        Private fieldTypeIdField As Integer
        
        Private filterTypeField As String
        
        Private formatStringField As String
        
        Private friendlyNameField As String
        
        Private guidsField() As System.Guid
        
        Private guidField As System.Guid
        
        Private importBehaviorField As System.Nullable(Of ImportBehaviorChoice)
        
        Private isAdditionalFileFieldField As Boolean
        
        Private isArtifactBaseFieldField As Boolean
        
        Private isAvailableInChoiceTreeField As Boolean
        
        Private isAvailableToAssociativeObjectsField As Boolean
        
        Private isEditableField As Boolean
        
        Private isGroupByEnabledField As Boolean
        
        Private isIndexEnabledField As Boolean
        
        Private isLinkedField As Boolean
        
        Private isRemovableField As Boolean
        
        Private isRequiredField As Boolean
        
        Private isSortableField As Boolean
        
        Private isVisibleField As Boolean
        
        Private keywordsField As String
        
        Private linkTypeField As Boolean
        
        Private maxLengthField As System.Nullable(Of Integer)
        
        Private notesField As String
        
        Private paneField As PaneElement
        
        Private relationalIndexViewArtifactIDField As System.Nullable(Of Integer)
        
        Private sourceFieldArtifactIdField As System.Nullable(Of Integer)
        
        Private useUnicodeEncodingField As Boolean
        
        Private widthField As String
        
        Private wrappingField As Boolean
        
        Private allowPivotField As Boolean
        
        Private allowGroupByField As Boolean
        
        Private availableInViewerField As Boolean
        
        Private popupPickerViewField As System.Nullable(Of Integer)
        
        Private fieldTreeViewField As System.Nullable(Of Integer)
        
        Private siblingFieldArtifactIDField As System.Nullable(Of Integer)
        
        Private autoAddChoicesField As System.Nullable(Of Boolean)
        
        Private applicationVersionField As String
        
        '''<remarks/>
        Public Property AllowHTML() As Boolean
            Get
                Return Me.allowHTMLField
            End Get
            Set
                Me.allowHTMLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactId() As Integer
            Get
                Return Me.artifactIdField
            End Get
            Set
                Me.artifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactViewFieldId() As Integer
            Get
                Return Me.artifactViewFieldIdField
            End Get
            Set
                Me.artifactViewFieldIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AssociativeArtifactTypeId() As System.Nullable(Of Integer)
            Get
                Return Me.associativeArtifactTypeIdField
            End Get
            Set
                Me.associativeArtifactTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Code")>  _
        Public Property Codes() As CodeElement()
            Get
                Return Me.codesField
            End Get
            Set
                Me.codesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property CodeTypeId() As System.Nullable(Of Integer)
            Get
                Return Me.codeTypeIdField
            End Get
            Set
                Me.codeTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ConnectorFieldArtifactId() As System.Nullable(Of Integer)
            Get
                Return Me.connectorFieldArtifactIdField
            End Get
            Set
                Me.connectorFieldArtifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayName() As String
            Get
                Return Me.displayNameField
            End Get
            Set
                Me.displayNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayValueFalse() As String
            Get
                Return Me.displayValueFalseField
            End Get
            Set
                Me.displayValueFalseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DisplayValueTrue() As String
            Get
                Return Me.displayValueTrueField
            End Get
            Set
                Me.displayValueTrueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldArtifactTypeId() As Integer
            Get
                Return Me.fieldArtifactTypeIdField
            End Get
            Set
                Me.fieldArtifactTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldCategoryId() As Integer
            Get
                Return Me.fieldCategoryIdField
            End Get
            Set
                Me.fieldCategoryIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldTypeId() As Integer
            Get
                Return Me.fieldTypeIdField
            End Get
            Set
                Me.fieldTypeIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FilterType() As String
            Get
                Return Me.filterTypeField
            End Get
            Set
                Me.filterTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FormatString() As String
            Get
                Return Me.formatStringField
            End Get
            Set
                Me.formatStringField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FriendlyName() As String
            Get
                Return Me.friendlyNameField
            End Get
            Set
                Me.friendlyNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Guids")>  _
        Public Property Guids() As System.Guid()
            Get
                Return Me.guidsField
            End Get
            Set
                Me.guidsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Guid() As System.Guid
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ImportBehavior() As System.Nullable(Of ImportBehaviorChoice)
            Get
                Return Me.importBehaviorField
            End Get
            Set
                Me.importBehaviorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAdditionalFileField() As Boolean
            Get
                Return Me.isAdditionalFileFieldField
            End Get
            Set
                Me.isAdditionalFileFieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsArtifactBaseField() As Boolean
            Get
                Return Me.isArtifactBaseFieldField
            End Get
            Set
                Me.isArtifactBaseFieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailableInChoiceTree() As Boolean
            Get
                Return Me.isAvailableInChoiceTreeField
            End Get
            Set
                Me.isAvailableInChoiceTreeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsAvailableToAssociativeObjects() As Boolean
            Get
                Return Me.isAvailableToAssociativeObjectsField
            End Get
            Set
                Me.isAvailableToAssociativeObjectsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsEditable() As Boolean
            Get
                Return Me.isEditableField
            End Get
            Set
                Me.isEditableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsGroupByEnabled() As Boolean
            Get
                Return Me.isGroupByEnabledField
            End Get
            Set
                Me.isGroupByEnabledField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsIndexEnabled() As Boolean
            Get
                Return Me.isIndexEnabledField
            End Get
            Set
                Me.isIndexEnabledField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsLinked() As Boolean
            Get
                Return Me.isLinkedField
            End Get
            Set
                Me.isLinkedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsRemovable() As Boolean
            Get
                Return Me.isRemovableField
            End Get
            Set
                Me.isRemovableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsRequired() As Boolean
            Get
                Return Me.isRequiredField
            End Get
            Set
                Me.isRequiredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsSortable() As Boolean
            Get
                Return Me.isSortableField
            End Get
            Set
                Me.isSortableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsVisible() As Boolean
            Get
                Return Me.isVisibleField
            End Get
            Set
                Me.isVisibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LinkType() As Boolean
            Get
                Return Me.linkTypeField
            End Get
            Set
                Me.linkTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property MaxLength() As System.Nullable(Of Integer)
            Get
                Return Me.maxLengthField
            End Get
            Set
                Me.maxLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pane() As PaneElement
            Get
                Return Me.paneField
            End Get
            Set
                Me.paneField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property RelationalIndexViewArtifactID() As System.Nullable(Of Integer)
            Get
                Return Me.relationalIndexViewArtifactIDField
            End Get
            Set
                Me.relationalIndexViewArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SourceFieldArtifactId() As System.Nullable(Of Integer)
            Get
                Return Me.sourceFieldArtifactIdField
            End Get
            Set
                Me.sourceFieldArtifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseUnicodeEncoding() As Boolean
            Get
                Return Me.useUnicodeEncodingField
            End Get
            Set
                Me.useUnicodeEncodingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Width() As String
            Get
                Return Me.widthField
            End Get
            Set
                Me.widthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Wrapping() As Boolean
            Get
                Return Me.wrappingField
            End Get
            Set
                Me.wrappingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowPivot() As Boolean
            Get
                Return Me.allowPivotField
            End Get
            Set
                Me.allowPivotField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AllowGroupBy() As Boolean
            Get
                Return Me.allowGroupByField
            End Get
            Set
                Me.allowGroupByField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AvailableInViewer() As Boolean
            Get
                Return Me.availableInViewerField
            End Get
            Set
                Me.availableInViewerField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property PopupPickerView() As System.Nullable(Of Integer)
            Get
                Return Me.popupPickerViewField
            End Get
            Set
                Me.popupPickerViewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property FieldTreeView() As System.Nullable(Of Integer)
            Get
                Return Me.fieldTreeViewField
            End Get
            Set
                Me.fieldTreeViewField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SiblingFieldArtifactID() As System.Nullable(Of Integer)
            Get
                Return Me.siblingFieldArtifactIDField
            End Get
            Set
                Me.siblingFieldArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property AutoAddChoices() As System.Nullable(Of Boolean)
            Get
                Return Me.autoAddChoicesField
            End Get
            Set
                Me.autoAddChoicesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set
                Me.applicationVersionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class CodeElement
        
        Private artifactIdField As Integer
        
        Private guidField As System.Guid
        
        Private isActiveField As Boolean
        
        Private keywordsField As String
        
        Private nameField As String
        
        Private notesField As String
        
        Private oIHiliteStyleIDField As System.Nullable(Of Integer)
        
        Private orderField As Integer
        
        Private parentArtifactIdField As Integer
        
        Private parentIsCodeField As Boolean
        
        Private updateInSearchEngineField As Boolean
        
        Private applicationVersionField As String
        
        '''<remarks/>
        Public Property ArtifactId() As Integer
            Get
                Return Me.artifactIdField
            End Get
            Set
                Me.artifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Guid() As System.Guid
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsActive() As Boolean
            Get
                Return Me.isActiveField
            End Get
            Set
                Me.isActiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Keywords() As String
            Get
                Return Me.keywordsField
            End Get
            Set
                Me.keywordsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property OIHiliteStyleID() As System.Nullable(Of Integer)
            Get
                Return Me.oIHiliteStyleIDField
            End Get
            Set
                Me.oIHiliteStyleIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Order() As Integer
            Get
                Return Me.orderField
            End Get
            Set
                Me.orderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentArtifactId() As Integer
            Get
                Return Me.parentArtifactIdField
            End Get
            Set
                Me.parentArtifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentIsCode() As Boolean
            Get
                Return Me.parentIsCodeField
            End Get
            Set
                Me.parentIsCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdateInSearchEngine() As Boolean
            Get
                Return Me.updateInSearchEngineField
            End Get
            Set
                Me.updateInSearchEngineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplicationVersion() As String
            Get
                Return Me.applicationVersionField
            End Get
            Set
                Me.applicationVersionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Public Enum ImportBehaviorChoice
        
        '''<remarks/>
        LeaveBlankValuesUnchanged
        
        '''<remarks/>
        ReplaceBlankValuesWithIdentifier
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class PaneElement
        
        Private fieldIdField As Integer
        
        Private headerTextField As String
        
        Private imageFileDataField() As Byte
        
        Private imageFileNameField As String
        
        Private orderField As Integer
        
        Private srcField As String
        
        Private typeField As String
        
        Private viewIdField As Integer
        
        '''<remarks/>
        Public Property FieldId() As Integer
            Get
                Return Me.fieldIdField
            End Get
            Set
                Me.fieldIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HeaderText() As String
            Get
                Return Me.headerTextField
            End Get
            Set
                Me.headerTextField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property ImageFileData() As Byte()
            Get
                Return Me.imageFileDataField
            End Get
            Set
                Me.imageFileDataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ImageFileName() As String
            Get
                Return Me.imageFileNameField
            End Get
            Set
                Me.imageFileNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Order() As Integer
            Get
                Return Me.orderField
            End Get
            Set
                Me.orderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Src() As String
            Get
                Return Me.srcField
            End Get
            Set
                Me.srcField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ViewId() As Integer
            Get
                Return Me.viewIdField
            End Get
            Set
                Me.viewIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ObjectValidationResult
        
        Private objectNameField As String
        
        Private objectGuidField As System.Guid
        
        Private fieldToFieldsMapsField() As FieldToFieldsMap
        
        '''<remarks/>
        Public Property ObjectName() As String
            Get
                Return Me.objectNameField
            End Get
            Set
                Me.objectNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObjectGuid() As System.Guid
            Get
                Return Me.objectGuidField
            End Get
            Set
                Me.objectGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("FieldToFieldsMaps")>  _
        Public Property FieldToFieldsMaps() As FieldToFieldsMap()
            Get
                Return Me.fieldToFieldsMapsField
            End Get
            Set
                Me.fieldToFieldsMapsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ArtifactTypeIDToObjectGuids
        
        Private artifactTypeIDField As Integer
        
        Private objectGuidsField() As System.Guid
        
        '''<remarks/>
        Public Property ArtifactTypeID() As Integer
            Get
                Return Me.artifactTypeIDField
            End Get
            Set
                Me.artifactTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ObjectGuid", IsNullable:=false)>  _
        Public Property ObjectGuids() As System.Guid()
            Get
                Return Me.objectGuidsField
            End Get
            Set
                Me.objectGuidsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ObjectGuidToName
        
        Private objectGuidField As System.Guid
        
        Private objectNameField As String
        
        '''<remarks/>
        Public Property ObjectGuid() As System.Guid
            Get
                Return Me.objectGuidField
            End Get
            Set
                Me.objectGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObjectName() As String
            Get
                Return Me.objectNameField
            End Get
            Set
                Me.objectNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class FieldKVP
        
        Private keyField As String
        
        Private valueField As Object
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Value() As Object
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ResolveArtifact
        
        Private artifactIDField As Integer
        
        Private artifactTypeIDField As ApplicationArtifactType
        
        Private fieldsField() As FieldKVP
        
        Private actionField As ResolveAction
        
        '''<remarks/>
        Public Property ArtifactID() As Integer
            Get
                Return Me.artifactIDField
            End Get
            Set
                Me.artifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactTypeID() As ApplicationArtifactType
            Get
                Return Me.artifactTypeIDField
            End Get
            Set
                Me.artifactTypeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Fields() As FieldKVP()
            Get
                Return Me.fieldsField
            End Get
            Set
                Me.fieldsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Action() As ResolveAction
            Get
                Return Me.actionField
            End Get
            Set
                Me.actionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Public Enum ApplicationArtifactType
        
        '''<remarks/>
        Code
        
        '''<remarks/>
        Field
        
        '''<remarks/>
        Layout
        
        '''<remarks/>
        [Object]
        
        '''<remarks/>
        Rule
        
        '''<remarks/>
        Sync
        
        '''<remarks/>
        Tab
        
        '''<remarks/>
        View
        
        '''<remarks/>
        Script
        
        '''<remarks/>
        Instance
        
        '''<remarks/>
        CustomPage
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Public Enum ResolveAction
        
        '''<remarks/>
        Update
    End Enum
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Application)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationBase
        
        Private guidField As System.Guid
        
        Private idField As Integer
        
        Private inDevelopmentField As Boolean
        
        Private nameField As String
        
        Private versionField As String
        
        '''<remarks/>
        Public Property Guid() As System.Guid
            Get
                Return Me.guidField
            End Get
            Set
                Me.guidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property InDevelopment() As Boolean
            Get
                Return Me.inDevelopmentField
            End Get
            Set
                Me.inDevelopmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class Application
        Inherits ApplicationBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationArtifact
        
        Private workspaceIdField As Integer
        
        Private artifactIdField As Integer
        
        Private guidsField() As System.Guid
        
        Private nameField As String
        
        Private typeField As ApplicationArtifactType
        
        Private parentArtifactField As ApplicationArtifact
        
        Private conflictArtifactField As ApplicationArtifact
        
        Private statusField As StatusCode
        
        Private statusMessageField As String
        
        Private statusDetailsField As String
        
        Private applicationsField() As Application
        
        Private isMappableField As Boolean
        
        '''<remarks/>
        Public Property WorkspaceId() As Integer
            Get
                Return Me.workspaceIdField
            End Get
            Set
                Me.workspaceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactId() As Integer
            Get
                Return Me.artifactIdField
            End Get
            Set
                Me.artifactIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Guids() As System.Guid()
            Get
                Return Me.guidsField
            End Get
            Set
                Me.guidsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As ApplicationArtifactType
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ParentArtifact() As ApplicationArtifact
            Get
                Return Me.parentArtifactField
            End Get
            Set
                Me.parentArtifactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConflictArtifact() As ApplicationArtifact
            Get
                Return Me.conflictArtifactField
            End Get
            Set
                Me.conflictArtifactField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As StatusCode
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusMessage() As String
            Get
                Return Me.statusMessageField
            End Get
            Set
                Me.statusMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusDetails() As String
            Get
                Return Me.statusDetailsField
            End Get
            Set
                Me.statusDetailsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applications() As Application()
            Get
                Return Me.applicationsField
            End Get
            Set
                Me.applicationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsMappable() As Boolean
            Get
                Return Me.isMappableField
            End Get
            Set
                Me.isMappableField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Public Enum StatusCode
        
        '''<remarks/>
        UnknownError
        
        '''<remarks/>
        Created
        
        '''<remarks/>
        Updated
        
        '''<remarks/>
        NameConflict
        
        '''<remarks/>
        FriendlyNameConflict
        
        '''<remarks/>
        SharedByLockedApp
        
        '''<remarks/>
        MultipleFileField
        
        '''<remarks/>
        RenameConflict
        
        '''<remarks/>
        RenameFriendlyNameConflict
        
        '''<remarks/>
        Renamed
        
        '''<remarks/>
        Mapped
        
        '''<remarks/>
        NotUpdated
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class ApplicationInstallationResult
        
        Private applicationArtifactIDField As Integer
        
        Private messageField As String
        
        Private detailsField As String
        
        Private newApplicationArtifactsField() As ApplicationArtifact
        
        Private successField As Boolean
        
        Private updatedApplicationArtifactsField() As ApplicationArtifact
        
        Private statusApplicationArtifactsField() As ApplicationArtifact
        
        Private totalWorkspacesField As Integer
        
        Private workspaceIDField As Integer
        
        Private workspaceNameField As String
        
        '''<remarks/>
        Public Property ApplicationArtifactID() As Integer
            Get
                Return Me.applicationArtifactIDField
            End Get
            Set
                Me.applicationArtifactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Details() As String
            Get
                Return Me.detailsField
            End Get
            Set
                Me.detailsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NewApplicationArtifacts() As ApplicationArtifact()
            Get
                Return Me.newApplicationArtifactsField
            End Get
            Set
                Me.newApplicationArtifactsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Success() As Boolean
            Get
                Return Me.successField
            End Get
            Set
                Me.successField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdatedApplicationArtifacts() As ApplicationArtifact()
            Get
                Return Me.updatedApplicationArtifactsField
            End Get
            Set
                Me.updatedApplicationArtifactsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StatusApplicationArtifacts() As ApplicationArtifact()
            Get
                Return Me.statusApplicationArtifactsField
            End Get
            Set
                Me.statusApplicationArtifactsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalWorkspaces() As Integer
            Get
                Return Me.totalWorkspacesField
            End Get
            Set
                Me.totalWorkspacesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WorkspaceID() As Integer
            Get
                Return Me.workspaceIDField
            End Get
            Set
                Me.workspaceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WorkspaceName() As String
            Get
                Return Me.workspaceNameField
            End Get
            Set
                Me.workspaceNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class TargetField
        
        Private myNameField As String
        
        Private fieldGuidsField() As System.Guid
        
        Private artifactIDField As Integer
        
        '''<remarks/>
        Public Property MyName() As String
            Get
                Return Me.myNameField
            End Get
            Set
                Me.myNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldGuids() As System.Guid()
            Get
                Return Me.fieldGuidsField
            End Get
            Set
                Me.fieldGuidsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ArtifactID() As Integer
            Get
                Return Me.artifactIDField
            End Get
            Set
                Me.artifactIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class AppField
        
        Private myNameField As String
        
        Private fieldGuidsField() As System.Guid
        
        Private mappingCandidatesField() As TargetField
        
        Private mappedTargetFieldField As TargetField
        
        '''<remarks/>
        Public Property MyName() As String
            Get
                Return Me.myNameField
            End Get
            Set
                Me.myNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FieldGuids() As System.Guid()
            Get
                Return Me.fieldGuidsField
            End Get
            Set
                Me.fieldGuidsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MappingCandidates() As TargetField()
            Get
                Return Me.mappingCandidatesField
            End Get
            Set
                Me.mappingCandidatesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MappedTargetField() As TargetField
            Get
                Return Me.mappedTargetFieldField
            End Get
            Set
                Me.mappedTargetFieldField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class AppObject
        
        Private objectNameField As String
        
        Private objectGuidField As System.Guid
        
        Private appFieldsField() As AppField
        
        Private qualifiesForMappingField As Boolean
        
        '''<remarks/>
        Public Property ObjectName() As String
            Get
                Return Me.objectNameField
            End Get
            Set
                Me.objectNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ObjectGuid() As System.Guid
            Get
                Return Me.objectGuidField
            End Get
            Set
                Me.objectGuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AppFields() As AppField()
            Get
                Return Me.appFieldsField
            End Get
            Set
                Me.appFieldsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property QualifiesForMapping() As Boolean
            Get
                Return Me.qualifiesForMappingField
            End Get
            Set
                Me.qualifiesForMappingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.kCura.com/EDDS/TemplateManager")>  _
    Partial Public Class AppMappingData
        
        Private appObjectsField() As AppObject
        
        '''<remarks/>
        Public Property AppObjects() As AppObject()
            Get
                Return Me.appObjectsField
            End Get
            Set
                Me.appObjectsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetAppMappingDataForWorkspaceCompletedEventHandler(ByVal sender As Object, ByVal e As GetAppMappingDataForWorkspaceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAppMappingDataForWorkspaceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As AppMappingData
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),AppMappingData)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub InstallTemplateCompletedEventHandler(ByVal sender As Object, ByVal e As InstallTemplateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InstallTemplateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ApplicationInstallationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ApplicationInstallationResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub ResolveConflictsCompletedEventHandler(ByVal sender As Object, ByVal e As ResolveConflictsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ResolveConflictsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ApplicationInstallationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ApplicationInstallationResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetAvailableObjectsForMappingCompletedEventHandler(ByVal sender As Object, ByVal e As GetAvailableObjectsForMappingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAvailableObjectsForMappingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ObjectGuidToName()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ObjectGuidToName())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub GetAvailableFieldsForMappingCompletedEventHandler(ByVal sender As Object, ByVal e As GetAvailableFieldsForMappingCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetAvailableFieldsForMappingCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ObjectValidationResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ObjectValidationResult)
            End Get
        End Property
    End Class
End Namespace
