// -----------------------------------------------------------------------------------------------------
// <copyright file="UploadTapiBridgeTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents <see cref="UploadTapiBridge2"/> tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.DataExchange.NUnit.Integration
{
	using System;
	using System.Net;
	using System.Threading;

	using global::NUnit.Framework;

	using Relativity.DataExchange.TestFramework;
	using Relativity.DataExchange.Transfer;
	using Relativity.Testing.Identification;

	/// <summary>
	/// Represents <see cref="UploadTapiBridge2"/> tests.
	/// </summary>
	[TestFixture]
	[Feature.DataTransfer.ImportApi.Operations.ImportDocuments]
	[System.Diagnostics.CodeAnalysis.SuppressMessage(
		"Microsoft.Design",
		"CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable",
		Justification = "The test class handles the disposal.")]
	public class UploadTapiBridgeTests : TapiBridgeTestBase
	{
		private UploadTapiBridge2 tapiBridge;

		protected override TapiBridgeBase2 TapiBridge => this.tapiBridge;

		[IdentifiedTestCase("3b1d585f-a2ab-4a30-84ce-d0816e088333", TapiClient.None, false)]
		[IdentifiedTestCase("49c40e14-0fe6-429b-9690-63438d1c6a2e", TapiClient.Aspera, true)]
		[IdentifiedTestCase("f8cb64d1-4fe8-425c-8922-83a1646a5c9d", TapiClient.Aspera, false)]
		[IdentifiedTestCase("f4e8bc35-bf4c-47d2-9166-0603f4f34008", TapiClient.Direct, true)]
		[IdentifiedTestCase("c344b1c8-3c39-4aa1-97a1-6a32f1f1e18c", TapiClient.Direct, false)]
		[IdentifiedTestCase("50f47046-f2d0-4ffb-ba29-3b986233330b", TapiClient.Web, false)]
		[Category(TestCategories.ImportDoc)]
		[Category(TestCategories.Integration)]
		[Category(TestCategories.TransferApi)]
		public void ShouldUploadTheFiles(TapiClient client, bool preserveTimestamps)
		{
			this.CheckSkipTest(client);
			this.GivenTheTapiClientSetting(client);
			this.GivenThePreserveFileTimestampsSetting(preserveTimestamps);
			this.GivenTheMaxFilesPerFolder(10);
			this.GivenTheNumberOfFiles(100);
			this.GivenTheAutoGeneratedDataset(this.TempDirectory.Directory);
			this.GivenTheTargetPath(
				System.IO.Path.Combine(
					System.IO.Path.Combine(this.TestParameters.FileShareUncPath, "NativeFileUploadTest"),
					$"{typeof(UploadTapiBridgeTests).Name}-{Guid.NewGuid()}"));
			this.GivenTheNativeFileTransfer();
			this.WhenExecutingTheJob();
			this.ThenTheTapiClientShouldEqualTheRequestedType();
			this.ThenTheFilesWereTransferred();
			this.ThenTheFileTimestampsArePreserved();
		}

		protected override void CreateTapiBridge()
		{
			var parameters = new UploadTapiBridgeParameters2
			{
				Credentials =
										 new NetworkCredential(
											 this.TestParameters.RelativityUserName,
											 this.TestParameters.RelativityPassword),
				FileShare = this.TestParameters.FileShareUncPath,
				MaxFilesPerFolder = this.MaxFilesPerFolder,
				MaxJobParallelism = 1,
				MaxJobRetryAttempts = 1,
				PreserveFileTimestamps = this.PreserveFileTimestamps,
				TargetPath = this.TargetPath,
				WaitTimeBetweenRetryAttempts = 0,
				WebCookieContainer = this.CookieContainer,
				WebServiceUrl = this.TestParameters.RelativityWebApiUrl.ToString(),
				WorkspaceId = this.TestParameters.WorkspaceId,
			};

			this.SetupTapiBridgeParameters(parameters);
			this.tapiBridge = new UploadTapiBridge2(parameters, this.TransferLog,  new NullAuthTokenProvider(), CancellationToken.None);
		}

		private void WhenExecutingTheJob()
		{
			var order = 0;
			foreach (var sourcePath in this.SourcePaths)
			{
				this.tapiBridge.AddPath(sourcePath, null, order++);
			}

			const bool KeepJobAlive = false;
			this.TapiBridge.WaitForTransfers("Waiting...", "Success", "Error", KeepJobAlive);
		}
	}
}