// -----------------------------------------------------------------------------------------------------
// <copyright file="FileLockedImportJobTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents file lock related import tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

using Relativity.ImportExport.UnitTestFramework;

namespace Relativity.Import.Client.NUnit.Integration
{
	using System.Data;

	using kCura.WinEDDS.TApi;

	using global::NUnit.Framework;

	/// <summary>
	/// Represents file lock related import tests.
	/// </summary>
	[TestFixture]
	public class FileLockedImportJobTests : ImportJobTestBase
	{
		/// <summary>
		/// Should import the files.
		/// </summary>
		/// <param name="client">
		/// The transfer client to force.
		/// </param>
		/// <param name="disableNativeLocationValidation">
		/// Specify whether to disable native location validation.
		/// </param>
		/// <param name="disableNativeValidation">
		/// Specify whether to disable native validation.
		/// </param>
		[Test]
		[TestCase(TapiClient.Direct, false, true)]
		[TestCase(TapiClient.Direct, true, true)]
		[TestCase(TapiClient.Web, false, true)]
		[TestCase(TapiClient.Web, true, true)]
		[TestCase(TapiClient.Aspera, false, true)]
		[TestCase(TapiClient.Aspera, true, true)]
		public void ShouldFailWhenTheFileIsLocked(TapiClient client, bool disableNativeLocationValidation, bool disableNativeValidation)
		{
			const int AutoGeneratedSourceFiles = 5;
			if (client == TapiClient.Aspera && TestSettings.SkipAsperaModeTests ||
			    client == TapiClient.Direct && TestSettings.SkipDirectModeTests)
			{
				Assert.Ignore(TestSettings.SkipTestMessage, $"{client}");
			}

			// Intentionally provide an invalid file before adding valid ones.
			this.GivenTheAutoGeneratedDatasetToImport(AutoGeneratedSourceFiles, false);
			this.GivenTheSourceFileIsLocked(2);
			this.GivenTheImportJob();
			this.GivenTheStandardConfigSettings(client, disableNativeLocationValidation, disableNativeValidation);
			this.WhenExecutingTheJob();
			this.ThenTheImportJobIsNotSuccessful(0, AutoGeneratedSourceFiles, true);

			// The exact value is impossible to predict.
			this.ThenTheImportProgressEventsCountIsNonZero();
			this.ThenTheImportMessageCountIsNonZero();
		}

		/// <inheritdoc />
		protected override void OnPreTearDown()
		{
			foreach (DataRow file in this.SourceData.Rows)
			{
				var filePath = file[1].ToString();
				ImportJobTestBase.ChangeFileFullPermissions(filePath, true);
			}

			base.OnPreTearDown();
		}
	}
}