// ----------------------------------------------------------------------------
// <copyright file="PositiveImportJobTests.cs" company="kCura Corp">
//   kCura Corp (C) 2017 All Rights Reserved.
// </copyright>
// ----------------------------------------------------------------------------

namespace kCura.WinEDDS.TApi.NUnit.Integration
{
    using global::NUnit.Framework;

    using global::Relativity.Transfer.UnitTestFramework;

    /// <summary>
    /// Represents positive import job tests.
    /// </summary>
    [TestFixture]
    public class PositiveImportJobTests : ImportJobTestBase
    {
        /// <summary>
        /// Should import the files.
        /// </summary>
        /// <param name="forceClient">
        /// The transfer client to force.
        /// </param>
        /// <param name="workspaceWithAspera">
        /// Specify whether to use a workspace with Aspera configured.
        /// </param>
        /// <param name="disableNativeLocationValidation">
        /// Specify whether to disable native location validation.
        /// </param>
        /// <param name="disableNativeValidation">
        /// Specify whether to disable native validation.
        /// </param>
        [Test]
        [TestCase(TapiClient.Direct, false, true, true)]
        [TestCase(TapiClient.Web, false, true, true)]
        [TestCase(TapiClient.Aspera, true, true, true)]
        public void ShouldImportTheFiles(
            TapiClient forceClient,
            bool workspaceWithAspera,
            bool disableNativeLocationValidation,
            bool disableNativeValidation)
        {
            this.GivenTheAutoGeneratedDatasetToImport(5, true);
            this.GivenTheTestInstance(TestEnvironment.OnPremisePrivateCloud);
            this.GivenTheWorkspaceId(
                workspaceWithAspera
                    ? this.TestInstance.WorkspaceIdWithAspera
                    : this.TestInstance.WorkspaceIdWithoutAspera);
            this.GivenTheImportJob();
            this.GivenTheStandardConfigSettings(forceClient, disableNativeLocationValidation, disableNativeValidation);
            this.WhenExecutingTheJob();
            this.ThenTheImportJobIsSuccessful();
            this.ThenTheImportMessageCountIsNonZero();
            this.ThenTheImportProgressEventsAreRaised();
        }
    }
}