// -----------------------------------------------------------------------------------------------------
// <copyright file="PositiveImportJobTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents positive import job tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.Import.Client.NUnit.Integration
{
	using kCura.WinEDDS.TApi;

	using global::NUnit.Framework;

	using Relativity.ImportExport.UnitTestFramework;

	/// <summary>
	/// Represents positive import job tests.
	/// </summary>
	[TestFixture]
	public class PositiveImportJobTests : ImportJobTestBase
	{
		/// <summary>
		/// Should import the files.
		/// </summary>
		/// <param name="client">
		/// The transfer client to force.
		/// </param>
		/// <param name="disableNativeLocationValidation">
		/// Specify whether to disable native location validation.
		/// </param>
		/// <param name="disableNativeValidation">
		/// Specify whether to disable native validation.
		/// </param>
		[Test]
		[TestCase(TapiClient.Direct, true, true)]
		[TestCase(TapiClient.Web, true, true)]
		[TestCase(TapiClient.Aspera, true, true)]
		public void ShouldImportTheFiles(
			TapiClient client,
			bool disableNativeLocationValidation,
			bool disableNativeValidation)
		{
			if (client == TapiClient.Aspera && TestSettings.SkipAsperaModeTests ||
			    client == TapiClient.Direct && TestSettings.SkipDirectModeTests)
			{
				Assert.Ignore(TestSettings.SkipTestMessage, $"{client}");
			}

			this.GivenTheAutoGeneratedDatasetToImport(5, true);
			this.GivenTheImportJob();
			this.GivenTheStandardConfigSettings(client, disableNativeLocationValidation, disableNativeValidation);
			this.WhenExecutingTheJob();
			this.ThenTheImportJobIsSuccessful();
			this.ThenTheImportMessageCountIsNonZero();
			this.ThenTheImportProgressEventsAreRaised();
		}
	}
}