// -----------------------------------------------------------------------------------------------------
// <copyright file="TapiBridgeTestsBase.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents <see cref="TapiBridgeBase"/> tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.Import.Client.NUnit.Integration
{
	using System;
	using System.Net;

	using kCura.WinEDDS.TApi;

	using Moq;

	using global::NUnit.Framework;

	using Relativity.ImportExport.UnitTestFramework;
	using Relativity.Transfer;

	/// <summary>
	/// Base class for the tests for the <see cref="TapiBridgeBase"/> class.
	/// </summary>
	public abstract class TapiBridgeTestsBase
	{
		/// <summary>
		/// The minimum test file length [1KB]
		/// </summary>
		private const int MinTestFileLength = 1024;

		/// <summary>
		/// The maximum test file length [10KB]
		/// </summary>
		private const int MaxTestFileLength = 10 * MinTestFileLength;

		/// <summary>
		/// The thread synchronization root backing.
		/// </summary>
		private static readonly object SyncRoot = new object();

		/// <summary>
		/// The test directory backing.
		/// </summary>
		private TempDirectory testDirectory;

		/// <summary>
		/// The file count.
		/// </summary>
		private int fileCount;

		/// <summary>
		/// The number of files transferred.
		/// </summary>
		private int filesTransferred;

		/// <summary>
		/// The total number of warnings.
		/// </summary>
		private int warnings;

		/// <summary>
		/// The total number of fatal errors
		/// </summary>
		private int fatalErrors;

		/// <summary>
		/// The test setup.
		/// </summary>
		[SetUp]
		public void Setup()
		{
			ServicePointManager.SecurityProtocol =
				SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11
				| SecurityProtocolType.Tls12;
			this.SourcePaths = new global::System.Collections.Generic.List<string>();
			this.MaxFilesPerFolder = 1000;
			this.TargetPath = null;
			this.CookieContainer = new CookieContainer();
			this.fileCount = 0;
			this.filesTransferred = 0;
			this.fatalErrors = 0;
			this.warnings = 0;
			this.testDirectory = new TempDirectory { ClearReadOnlyAttributes = true };
			this.testDirectory.Create();
			this.TransferLog = new Mock<ITransferLog>();
		}

		/// <summary>
		/// The test tear down.
		/// </summary>
		[TearDown]
		public void TearDown()
		{
			this.NativeFileTransfer?.Dispose();
			this.testDirectory?.Dispose();
		}

		/// <summary>
		/// The cookie container.
		/// </summary>
		/// <value>
		/// The <see cref="CookieContainer"/> instance.
		/// </value>
		protected CookieContainer CookieContainer
		{
			get;
			private set;
		}

		/// <summary>
		/// The maximum number of files per folder.
		/// </summary>
		/// <value>
		/// The file count.
		/// </value>
		protected int MaxFilesPerFolder
		{
			get;
			private set;
		}

		/// <summary>
		/// The native file transfer class.
		/// </summary>
		protected abstract TapiBridgeBase NativeFileTransfer
		{
			get;
		}

		/// <summary>
		/// The target path.
		/// </summary>
		/// <value>
		/// The full path.
		/// </value>
		protected string TargetPath
		{
			get;
			private set;
		}

		/// <summary>
		/// The test directory.
		/// </summary>
		/// <value>
		/// The full path.
		/// </value>
		protected string TestDirectory => this.testDirectory.Directory;

		/// <summary>
		/// The mock transfer log.
		/// </summary>
		/// <value>
		/// The mock <see cref="ITransferLog"/> instance.
		/// </value>
		protected Mock<ITransferLog> TransferLog
		{
			get;
			private set;
		}

		/// <summary>
		/// The list of source paths.
		/// </summary>
		protected System.Collections.Generic.IList<string> SourcePaths
		{
			get;
			private set;
		}

		/// <summary>
		/// Given the maximum number of files per folder.
		/// </summary>
		/// <param name="value">
		/// The max value.
		/// </param>
		protected void GivenTheMaxFilesPerFolder(int value)
		{
			this.MaxFilesPerFolder = value;
		}

		/// <summary>
		/// The given the number of files to generate.
		/// </summary>
		/// <param name="value">
		/// The number of files.
		/// </param>
		protected void GivenTheNumberOfFiles(int value)
		{
			this.fileCount = value;
		}

		/// <summary>
		/// Given the dataset is auto-generated by the number of specified files.
		/// </summary>
		/// <param name="directory">
		/// The directory.
		/// </param>
		protected void GivenTheAutoGeneratedDataset(string directory)
		{
			if (!System.IO.Directory.Exists(directory))
			{
				System.IO.Directory.CreateDirectory(directory);
			}

			for (var i = 0; i < this.fileCount; i++)
			{
				var file = TestHelper.NextTextFile(
					MinTestFileLength,
					MaxTestFileLength,
					directory,
					false);
				this.SourcePaths.Add(file);
			}
		}

		/// <summary>
		/// Given the target path.
		/// </summary>
		/// <param name="value">
		/// The value.
		/// </param>
		protected void GivenTheTargetPath(string value)
		{
			this.TargetPath = value;
		}

		/// <summary>
		/// Given the <see cref="TapiBridgeBase"/> class.
		/// </summary>
		protected void GivenTheNativeFileTransfer()
		{
			this.CreateTapiBridge();
			this.NativeFileTransfer.TapiFatalError += (sender, args) =>
			{
				lock (SyncRoot)
				{
					this.fatalErrors++;
				}
			};

			this.NativeFileTransfer.TapiWarningMessage += (sender, args) =>
			{
				lock (SyncRoot)
				{
					this.warnings++;
				}
			};

			this.NativeFileTransfer.TapiProgress += (sender, args) =>
			{
				lock (SyncRoot)
				{
					this.filesTransferred++;
				}
			};
		}

		protected abstract void CreateTapiBridge();

		/// <summary>
		/// Then all the files were transferred.
		/// </summary>
		protected void ThenTheFilesWereTransferred()
		{
			Console.WriteLine($"Files Transferred: {this.filesTransferred}");
			Assert.That(this.fatalErrors, Is.EqualTo(0));
			Assert.That(this.warnings, Is.EqualTo(0));
			Assert.That(this.filesTransferred, Is.EqualTo(this.fileCount));
		}
	}
}