//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relativity.Import.Export.Services
{
	/// <summary>
	/// Defines constants for the well-known Relativity column source types, including computed, artifact, main table, and no database column.
	/// </summary>
	public enum ColumnSourceType : int
	{

		Computed = 0,

		Artifact = 1,

		MetadataJoin = 2,

		MainTable = 3,

		NoDatabaseColumn = 4,
	}
}