//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
namespace Relativity.Import.Export.Services
{
	public enum FieldTypeHelperFieldType
	{

		Empty = -1,

		Varchar = 0,

		Integer = 1,

		Date = 2,

		Boolean = 3,

		Text = 4,

		Code = 5,

		Decimal = 6,

		Currency = 7,

		MultiCode = 8,

		File = 9,

		Object = 10,

		User = 11,

		LayoutText = 12,

		Objects = 13,

		OffTableText = 14,
	}
}