//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
namespace Relativity.Import.Export.Services
{
	public class FolderInfo
	{
		public int ArtifactID { get; set; }

		public string Name { get; set; }

		public Relativity.Import.Export.Services.FolderInfo Parent { get; set; }

		public int ParentArtifactID { get; set; }
	}
}