//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relativity.DataExchange.Service
{
	/// <summary>
	/// Defines constants for the well-known import overwrite behaviors, including append, overlay, and append/overlay.
	/// </summary>
	public enum ImportOverwriteType
	{

		Append = 0,

		Overlay = 1,

		AppendOverlay = 2,
	}
}