//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Relativity.DataExchange.Service
{
	/// <summary>
	/// Defines constants for the well-known parent reflection types, including empty, parent, and grandparent.
	/// </summary>
	public enum ParentReflectionType
	{

		Empty = -1,

		Parent = 1,

		GrandParent = 2,
	}
}