// -----------------------------------------------------------------------------------------------------
// <copyright file="DownloadTapiBridgeTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents <see cref="DownloadTapiBridge2"/> tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.Import.Export.NUnit.Integration
{
	using System;
	using System.Net;
	using System.Threading;

	using global::NUnit.Framework;

	using Relativity.Import.Export.TestFramework;
	using Relativity.Import.Export.Transfer;
	using Relativity.Testing.Identification;
	using Relativity.Transfer;

	/// <summary>
	/// Represents <see cref="DownloadTapiBridge2"/> tests.
	/// </summary>
	[TestFixture]
	[Feature.DataTransfer.TransferApi]
	[System.Diagnostics.CodeAnalysis.SuppressMessage(
		"Microsoft.Design",
		"CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable",
		Justification = "The test class handles the disposal.")]
	public class DownloadTapiBridgeTests : TapiBridgeTestBase
	{
		private DownloadTapiBridge2 tapiBridge;

		protected override TapiBridgeBase2 TapiBridge => this.tapiBridge;

		[IdentifiedTestCase("b892be9b-c0cb-4e0b-aea8-9c1c9a601834", TapiClient.None, false)]
		[IdentifiedTestCase("8c7a5c0c-77eb-40c5-beb7-0a3f009a2472", TapiClient.Aspera, true)]
		[IdentifiedTestCase("74777b4f-24dc-4772-9ae9-4ef4b442da89", TapiClient.Aspera, false)]
		[IdentifiedTestCase("1616a14a-f239-42d4-b90d-c7c25d67d149", TapiClient.Direct, true)]
		[IdentifiedTestCase("87d185f9-15c6-4146-b306-0549774a2e0d", TapiClient.Direct, false)]
		[Category(TestCategories.Integration)]
		[Category(TestCategories.TransferApi)]
		public void ShouldDownloadTheFiles(TapiClient client, bool preserveTimestamps)
		{
			// Note: TapiClient.Web is skipped for now because it requires a significant amount
			//       of setup and configuration.
			this.CheckSkipTest(client);
			this.GivenTheTapiClientSetting(client);
			this.GivenThePreserveFileTimestampsSetting(preserveTimestamps);
			this.GivenTheMaxFilesPerFolder(10);
			this.GivenTheNumberOfFiles(100);
			this.GivenTheAutoGeneratedDataset(
				System.IO.Path.Combine(
					System.IO.Path.Combine(
						System.IO.Path.Combine(
							this.TestParameters.FileShareUncPath,
							$"{typeof(DownloadTapiBridgeTests).Name}-{Guid.NewGuid()}"))));
			this.GivenTheTargetPath(this.TempDirectory.Directory);
			this.GivenTheNativeFileTransfer();
			this.WhenExecutingTheJob();
			this.ThenTheTapiClientShouldEqualTheRequestedType();
			this.ThenTheFilesWereTransferred();
		}

		protected override void CreateTapiBridge()
		{
			var parameters = new TapiBridgeParameters2
								 {
									 Credentials =
										 new NetworkCredential(
											 this.TestParameters.RelativityUserName,
											 this.TestParameters.RelativityPassword),
									 FileShare = this.TestParameters.FileShareUncPath,
									 MaxJobParallelism = 1,
									 MaxJobRetryAttempts = 1,
									 PreserveFileTimestamps = this.PreserveFileTimestamps,
									 TargetPath = this.TargetPath,
									 WaitTimeBetweenRetryAttempts = 0,
									 WebCookieContainer = this.CookieContainer,
									 WebServiceUrl = this.TestParameters.RelativityWebApiUrl.ToString(),
									 WorkspaceId = this.TestParameters.WorkspaceId,
								 };

			this.SetupTapiBridgeParameters(parameters);
			this.tapiBridge = new DownloadTapiBridge2(parameters, this.TransferLog, CancellationToken.None);
		}

		private void WhenExecutingTheJob()
		{
			var order = 0;
			foreach (var sourcePath in this.SourcePaths)
			{
				this.tapiBridge.AddPath(new TransferPath
				{
					Order = order,
					SourcePath = sourcePath,
					TargetPath = this.tapiBridge.TargetPath,
				});
			}

			this.TapiBridge.WaitForTransferJob();
		}
	}
}