// -----------------------------------------------------------------------------------------------------
// <copyright file="UploadTapiBridgeTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents <see cref="UploadTapiBridge"/> tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.Import.Export.NUnit.Integration
{
	using System;
	using System.Net;
	using System.Threading;

	using global::NUnit.Framework;

	using Relativity.Import.Export.TestFramework;
	using Relativity.Import.Export.Transfer;

	/// <summary>
	/// Represents <see cref="UploadTapiBridge"/> tests.
	/// </summary>
	[TestFixture]
	[System.Diagnostics.CodeAnalysis.SuppressMessage(
		"Microsoft.Design",
		"CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable",
		Justification = "The test class handles the disposal.")]
	public class UploadTapiBridgeTests : TapiBridgeTestBase
	{
		private UploadTapiBridge tapiBridge;

		protected override TapiBridgeBase TapiBridge => this.tapiBridge;

		[Test]
		[TestCase(TapiClient.None, false)]
		[TestCase(TapiClient.Aspera, true)]
		[TestCase(TapiClient.Aspera, false)]
		[TestCase(TapiClient.Direct, true)]
		[TestCase(TapiClient.Direct, false)]
		[TestCase(TapiClient.Web, false)]
		[Category(TestCategories.ImportDoc)]
		[Category(TestCategories.Integration)]
		[Category(TestCategories.TransferApi)]
		public void ShouldUploadTheFiles(TapiClient client, bool preserveTimestamps)
		{
			this.CheckSkipTest(client);
			this.GivenTheTapiClientSetting(client);
			this.GivenThePreserveFileTimestampsSetting(preserveTimestamps);
			this.GivenTheMaxFilesPerFolder(10);
			this.GivenTheNumberOfFiles(100);
			this.GivenTheAutoGeneratedDataset(this.TempDirectory.Directory);
			this.GivenTheTargetPath(
				System.IO.Path.Combine(
					System.IO.Path.Combine(this.TestParameters.FileShareUncPath, "NativeFileUploadTest"),
					$"{typeof(UploadTapiBridgeTests).Name}-{Guid.NewGuid()}"));
			this.GivenTheNativeFileTransfer();
			this.WhenExecutingTheJob();
			this.ThenTheTapiClientShouldEqualTheRequestedType();
			this.ThenTheFilesWereTransferred();
			this.ThenTheFileTimestampsArePreserved();
		}

		protected override void CreateTapiBridge()
		{
			var parameters = new UploadTapiBridgeParameters
				                 {
					                 Credentials =
						                 new NetworkCredential(
							                 this.TestParameters.RelativityUserName,
							                 this.TestParameters.RelativityPassword),
					                 FileShare = this.TestParameters.FileShareUncPath,
									 MaxFilesPerFolder = this.MaxFilesPerFolder,
					                 MaxJobParallelism = 1,
					                 MaxJobRetryAttempts = 1,
					                 PreserveFileTimestamps = this.PreserveFileTimestamps,
					                 TargetPath = this.TargetPath,
					                 WaitTimeBetweenRetryAttempts = 0,
					                 WebCookieContainer = this.CookieContainer,
					                 WebServiceUrl = this.TestParameters.RelativityWebApiUrl.ToString(),
					                 WorkspaceId = this.TestParameters.WorkspaceId
				                 };

			this.SetupTapiBridgeParameters(parameters);
			this.tapiBridge = new UploadTapiBridge(parameters, this.TransferLog, CancellationToken.None);
		}

		private void WhenExecutingTheJob()
		{
			var order = 0;
			foreach (var sourcePath in this.SourcePaths)
			{
				this.tapiBridge.AddPath(sourcePath, null, order++);
			}

			this.TapiBridge.WaitForTransferJob();
		}
	}
}