// -----------------------------------------------------------------------------------------------------
// <copyright file="FileLockedImportJobTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents file lock related import tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.DataExchange.Import.NUnit.Integration
{
	using System.Collections.Generic;
	using System.Data;
	using System.Data.Common;
	using System.IO;
	using System.Security.AccessControl;
	using System.Security.Principal;

	using global::NUnit.Framework;

	using Relativity.DataExchange.TestFramework;
	using Relativity.DataExchange.Transfer;
	using Relativity.Testing.Identification;

	[TestFixture]
	[Feature.DataTransfer.ImportApi.Operations.ImportDocuments]
	public class FileLockedImportJobTests : NativeImportJobTestBase
	{
		[Category(TestCategories.ImportDoc)]
		[Category(TestCategories.Integration)]
		[Category(TestCategories.TransferApi)]
		[IdentifiedTestCase("e41a8da9-c562-467e-a638-5afa05b59224", TapiClient.Direct, false, true)]
		[IdentifiedTestCase("4bfa1999-7ba2-4c66-bd07-cfb9dbe56b23", TapiClient.Direct, true, true)]
		[IdentifiedTestCase("1b7e9bbc-eb2e-4eae-9d07-11a03778fa7d", TapiClient.Web, false, true)]
		[IdentifiedTestCase("267f10e9-418e-4ec7-83ca-19dadf604531", TapiClient.Web, true, true)]
		[IdentifiedTestCase("269aca91-7acd-42bd-96f2-2422bf9f4c4b", TapiClient.Aspera, false, true)]
		[IdentifiedTestCase("f3661eb4-ca4a-4b36-b0c5-0042780c184a", TapiClient.Aspera, true, true)]
		public void ShouldFailWhenTheFileIsLocked(TapiClient client, bool disableNativeLocationValidation, bool disableNativeValidation)
		{
			TapiClientModeAvailabilityChecker.SkipTestIfModeNotAvailable(AssemblySetup.TestParameters, client);

			ForceClient(client);
			kCura.WinEDDS.Config.ConfigSettings["DisableNativeLocationValidation"] = disableNativeLocationValidation;
			kCura.WinEDDS.Config.ConfigSettings["DisableNativeValidation"] = disableNativeValidation;

			this.GivenTheImportJob();
			this.GivenDefaultNativeDocumentImportJob();

			const int AutoGeneratedSourceFiles = 5;
			List<string> files = this.GetRandomTextFiles(maxFiles: AutoGeneratedSourceFiles, includeReadOnlyFiles: true);
			using (DataTable table = GivenDefaultNativeTable())
			using (DbDataReader reader = this.GivenDbDataReaderForNativeTable(table, files))
			{
				string filePath = table.Rows[2][1].ToString();
				DenyFileAccess(filePath);

				// act
				this.WhenExecutingTheJob(reader);
			}

			this.ThenTheImportJobFailedWithFatalError(0, AutoGeneratedSourceFiles);

			// The exact value is impossible to predict.
			Assert.That(this.TestJobResult.ProgressCompletedRows, Has.Count.Positive);
			Assert.That(this.TestJobResult.JobMessages, Has.Count.Positive);
		}

		[TearDown]
		public void TeardownFileLockedImportJobTests()
		{
			string[] files = Directory.GetFiles(this.TempDirectory.Directory, "*");
			foreach (var file in files)
			{
				RestoreFileAccess(file);
			}
		}

		protected static void DenyFileAccess(string path)
		{
			FileSecurity accessControl = File.GetAccessControl(path);
			var sid = new SecurityIdentifier(WellKnownSidType.AuthenticatedUserSid, null);
			accessControl.AddAccessRule(
				new FileSystemAccessRule(
					sid,
					FileSystemRights.Read | FileSystemRights.Write,
					AccessControlType.Deny));
			File.SetAccessControl(path, accessControl);
		}

		protected static void RestoreFileAccess(string path)
		{
			FileSecurity accessControl = File.GetAccessControl(path);
			var sid = new SecurityIdentifier(WellKnownSidType.AuthenticatedUserSid, null);
			accessControl.RemoveAccessRule(
				new FileSystemAccessRule(
					sid,
					FileSystemRights.Read | FileSystemRights.Write,
					AccessControlType.Deny));
			File.SetAccessControl(path, accessControl);
		}
	}
}