// -----------------------------------------------------------------------------------------------------
// <copyright file="PositiveImportJobTests.cs" company="Relativity ODA LLC">
//   © Relativity All Rights Reserved.
// </copyright>
// <summary>
//   Represents positive import job tests.
// </summary>
// -----------------------------------------------------------------------------------------------------

namespace Relativity.Import.Client.NUnit.Integration
{
	using global::NUnit.Framework;

	using Relativity.Import.Export.TestFramework;
	using Relativity.Import.Export.Transfer;

	using Relativity.Testing.Identification;

	/// <summary>
	/// Represents positive import job tests.
	/// </summary>
	[TestFixture]
	[Feature.DataTransfer.ImportApi.Operations.ImportDocuments]
	public class PositiveImportJobTests : ImportJobTestBase
	{
		/// <summary>
		/// Should import the files.
		/// </summary>
		/// <param name="client">
		/// The transfer client to force.
		/// </param>
		/// <param name="disableNativeLocationValidation">
		/// Specify whether to disable native location validation.
		/// </param>
		/// <param name="disableNativeValidation">
		/// Specify whether to disable native validation.
		/// </param>
		[Category(TestCategories.ImportDoc)]
		[Category(TestCategories.Integration)]
		[Category(TestCategories.TransferApi)]
		[IdentifiedTestCase("99aa6c4b-029c-41f2-840b-1ef14a295047", TapiClient.Direct, true, true)]
		[IdentifiedTestCase("77030f47-ff53-4445-a112-0a45fa80fc6e", TapiClient.Web, true, true)]
		[IdentifiedTestCase("2c8adb7d-c787-4364-a930-ae8fff045e52", TapiClient.Aspera, true, true)]
		public void ShouldImportTheFiles(
			TapiClient client,
			bool disableNativeLocationValidation,
			bool disableNativeValidation)
		{
			if ((client == TapiClient.Aspera && this.TestParameters.SkipAsperaModeTests) ||
				(client == TapiClient.Direct && this.TestParameters.SkipDirectModeTests))
			{
				Assert.Ignore(TestStrings.SkipTestMessage, $"{client}");
			}

			this.GivenTheAutoGeneratedDatasetToImport(5, true);
			this.GivenTheImportJob();
			GivenTheStandardConfigSettings(client, disableNativeLocationValidation, disableNativeValidation);
			this.WhenExecutingTheJob();
			this.ThenTheImportJobIsSuccessful();
			this.ThenTheImportMessageCountIsNonZero();
			this.ThenTheImportProgressEventsAreRaised();
		}
	}
}