'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2300
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2300.
'
Namespace kCura.EDDS.WebAPI.FieldQueryBase
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FieldQuerySoap", [Namespace]:="http://foley.com/EDDS/FieldQuery")>  _
    Public Class FieldQuery
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/EDDS/WebAPI/FieldQuery.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://foley.com/EDDS/FieldQuery/RetrieveDisplayFieldNameByFieldCategoryID", RequestNamespace:="http://foley.com/EDDS/FieldQuery", ResponseNamespace:="http://foley.com/EDDS/FieldQuery", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveDisplayFieldNameByFieldCategoryID(ByVal fieldCategoryID As Integer, ByVal contextArtifactID As Integer) As String
            Dim results() As Object = Me.Invoke("RetrieveDisplayFieldNameByFieldCategoryID", New Object() {fieldCategoryID, contextArtifactID})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveDisplayFieldNameByFieldCategoryID(ByVal fieldCategoryID As Integer, ByVal contextArtifactID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveDisplayFieldNameByFieldCategoryID", New Object() {fieldCategoryID, contextArtifactID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveDisplayFieldNameByFieldCategoryID(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://foley.com/EDDS/FieldQuery/RetrieveAllMappable", RequestNamespace:="http://foley.com/EDDS/FieldQuery", ResponseNamespace:="http://foley.com/EDDS/FieldQuery", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveAllMappable(ByVal caseID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetrieveAllMappable", New Object() {caseID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveAllMappable(ByVal caseID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveAllMappable", New Object() {caseID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveAllMappable(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://foley.com/EDDS/FieldQuery/RetrieveAll", RequestNamespace:="http://foley.com/EDDS/FieldQuery", ResponseNamespace:="http://foley.com/EDDS/FieldQuery", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function RetrieveAll(ByVal caseID As Integer) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("RetrieveAll", New Object() {caseID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '<remarks/>
        Public Function BeginRetrieveAll(ByVal caseID As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("RetrieveAll", New Object() {caseID}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndRetrieveAll(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),System.Data.DataSet)
        End Function
    End Class
End Namespace
